import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { access, readFile, readdir } from "node:fs/promises";
import path from "node:path";
import test from "node:test";

import { parseTOML } from "confbox";

const root = path.resolve(import.meta.dirname, "..");
const read = (relative: string) => readFile(path.join(root, relative), "utf8");

const headings = [
  "# 目的と完了条件",
  "# 現状と根拠",
  "# 実装方針",
  "# インターフェースとデータフロー",
  "# テスト計画",
  "# 前提・対象外・リスク",
];

const workflowSkillNames = ["plan", "implement", "review", "workflow-retrospective", "workflow-performance-audit"];
const allSkillNames = [...workflowSkillNames, "git-commit-push-pr", "kabeuchi"];

function parseTomlSource(relative: string, source: string): Record<string, unknown> {
  try {
    return parseTOML(source) as Record<string, unknown>;
  } catch (error) {
    throw new Error(`Failed to parse TOML: ${relative}`, { cause: error });
  }
}

function parseToml(relative: string): Record<string, unknown> {
  return parseTomlSource(
    relative,
    readFileSync(path.join(root, relative), "utf8"),
  );
}

test("TOML設定はNode内で解析される", () => {
  const environment = parseToml(".codex/environments/environment.toml");
  const config = parseToml(".codex/config.toml");
  const productAdvisor = parseToml(".codex/agents/product_advisor.toml");
  const projectExplorer = parseToml(".codex/agents/project_explorer.toml");
  const independentReviewer = parseToml(".codex/agents/independent_reviewer.toml");

  assert.equal(environment.name, "zoom-gov-contact-center-demo");
  assert.deepEqual(Object.keys(config.agents as Record<string, unknown>).sort(), [
    "independent_reviewer",
    "product_advisor",
    "project_explorer",
  ]);
  assert.equal(productAdvisor.model, "gpt-5.6-terra");
  assert.equal(projectExplorer.model, "gpt-5.6-luna");
  assert.equal(independentReviewer.model_reasoning_effort, "high");
});

test("TOML parserは直接依存として固定される", async () => {
  const packageJson = JSON.parse(await read("package.json")) as {
    devDependencies: Record<string, string>;
  };
  const packageLock = JSON.parse(await read("package-lock.json")) as {
    packages: Record<
      string,
      { devDependencies?: Record<string, string>; version?: string }
    >;
  };

  assert.equal(packageJson.devDependencies.confbox, "0.2.4");
  assert.equal(packageLock.packages[""].devDependencies?.confbox, "0.2.4");
  assert.equal(packageLock.packages["node_modules/confbox"].version, "0.2.4");
});

test("不正TOMLは対象path付きで失敗する", () => {
  assert.throws(
    () => parseTomlSource("fixtures/invalid.toml", "[invalid"),
    { message: "Failed to parse TOML: fixtures/invalid.toml" },
  );
});

test("Local Environmentはworktree setupとcheckout-scoped actionだけを共有する", async () => {
  const [environmentText, gitignore, parityReference] = await Promise.all([
    read(".codex/environments/environment.toml"),
    read(".gitignore"),
    read(".agents/skills/plan/references/parity-runner.md"),
  ]);
  const environment = parseToml(".codex/environments/environment.toml");
  const setup = environment.setup as { script: string };
  const cleanup = environment.cleanup as { script: string };
  const actions = environment.actions as Array<{ name: string; command: string }>;
  assert.match(environmentText, /^# THIS IS AUTOGENERATED\. DO NOT EDIT MANUALLY$/mu);
  assert.match(setup.script, /npm ci/u);
  assert.match(setup.script, /\.\/dev-compose\.sh prepare/u);
  assert.doesNotMatch(setup.script, /dev-compose\.sh (?:ensure|up)/u);
  assert.match(cleanup.script, /^\n?\.\/dev-compose\.sh cleanup\n?$/u);
  assert.deepEqual(
    actions.map((action) => action.name),
    [
      "Runtime status",
      "App start",
      "Web restart (explicit)",
      "Runtime stop",
      "Runtime contract tests",
    ],
  );
  for (const action of actions) {
    assert.doesNotMatch(action.command, /docker compose/u);
  }
  assert.match(gitignore, /^\/\.codex\/runtime\.local\.env$/mu);
  assert.match(gitignore, /^\/\.codex\/runtime-session\.local\.json$/mu);
  assert.match(gitignore, /^\/\.codex\/confirmation-session\.local\.json$/mu);
  assert.match(parityReference, /\.\/dev-compose\.sh ensure/u);
  assert.match(parityReference, /development-ports\.md/u);
  const ports = await read("docs/development/development-ports.md");
  assert.match(ports, /3001–3005／4001–4005/u);
});

test("PR templateは目的からCodexセッションまでの必須見出しを持つ", async () => {
  const template = await read(".github/PULL_REQUEST_TEMPLATE/ja.md");
  const headings = [...template.matchAll(/^## (.+)$/gmu)].map((match) => match[1]);
  assert.deepEqual(headings, [
    "目的",
    "変更内容",
    "影響範囲",
    "注意点 / リスク",
    "確認内容",
    "UI",
    "参考資料",
    "Codex セッション",
  ]);
  assert.match(template, /^### 自動確認$/mu);
  assert.match(template, /^### ユーザー動作確認$/mu);
  assert.match(template, /^- 対象外: UI変更なし$/mu);
  assert.match(template, /UI変更時はスクリーンショットまたは未添付理由を記載/u);
});

test("parity runnerとprototype helperはcanonical artifactsを検証する", async () => {
  const runnerPath = ".agents/skills/plan/scripts/parity-runner.mjs";
  const revisionPath = ".agents/skills/plan/scripts/prototype-revision.mjs";
  await Promise.all([
    access(path.join(root, runnerPath)),
    access(path.join(root, revisionPath)),
    access(path.join(root, ".agents/skills/plan/references/parity-runner.md")),
    access(path.join(root, "dev-prototype.sh")),
  ]);
  const [runnerFacade, runnerCore, workspace, revision] = await Promise.all([
    read(runnerPath),
    read(".agents/skills/plan/scripts/parity-runner-core.mjs"),
    read(".agents/skills/plan/scripts/parity-run-workspace.mjs"),
    read(revisionPath),
  ]);
  const runner = `${runnerFacade}\n${runnerCore}\n${workspace}`;
  for (const token of [
    "stateSetups",
    "rowProbeMap",
    "waitForVisible",
    "waitForHidden",
    "BrowserParityRunner",
    "performance-resource-timing",
    "browser-network-log",
    "window.scrollX/window.scrollY",
    "explicit-$implement-invocation",
    "validateEvidenceBundle",
    "prepare-run",
    "record-batch",
    "finalize-run",
  ]) {
    assert.ok(runner.includes(token), `parity runner omitted ${token}`);
  }
  assert.match(revision, /createHash\("sha256"\)/);
  assert.match(revision, /ui-contract\.json/);
  assert.match(revision, /productionBaseline\.sources/);
});

test("skill metadataは明示呼び出しを維持しUI説明の長さとpromptを満たす", async () => {
  for (const name of allSkillNames) {
    const yaml = await read(`.agents/skills/${name}/agents/openai.yaml`);
    assert.match(yaml, /allow_implicit_invocation: false/);
    assert.match(yaml, new RegExp(`default_prompt: "[^\\n]*\\$${name.replaceAll("-", "\\-")}`));
    const description = /^\s*short_description:\s*"([^"]+)"$/mu.exec(yaml)?.[1];
    assert.ok(description, `${name} is missing short_description`);
    assert.ok(description.length >= 25 && description.length <= 64, `${name} short_description length is invalid`);
  }
});

test("workflow-performance-auditは3ファイルだけのread-only明示skillで3値判定を持つ", async () => {
  const [skill, metadata, workflow, rootEntries, agentEntries, scriptEntries] = await Promise.all([
    read(".agents/skills/workflow-performance-audit/SKILL.md"),
    read(".agents/skills/workflow-performance-audit/agents/openai.yaml"),
    read("docs/development/codex-development-workflow.md"),
    readdir(path.join(root, ".agents/skills/workflow-performance-audit")),
    readdir(path.join(root, ".agents/skills/workflow-performance-audit/agents")),
    readdir(path.join(root, ".agents/skills/workflow-performance-audit/scripts")),
  ]);
  assert.deepEqual(rootEntries.sort(), ["SKILL.md", "agents", "scripts"]);
  assert.deepEqual(agentEntries, ["openai.yaml"]);
  assert.deepEqual(scriptEntries, ["analyze-sessions.mjs"]);
  assert.match(skill, /last four inclusive calendar days/u);
  assert.match(skill, /Do not create a report file/u);
  assert.match(skill, /ボトルネックあり/);
  assert.match(skill, /ボトルネックなし/);
  assert.match(skill, /判定不能/);
  assert.match(skill, /Never copy JSONL records, user messages, command text, tool payloads/);
  assert.match(metadata, /allow_implicit_invocation: false/);
  assert.doesNotMatch(metadata, /gpt-5\.|model|reasoning/);
  assert.match(workflow, /改善提案なし・現行workflowを変更しない/);
  assert.match(workflow, /標準フローへ自動追加せず/);
});

test("親モデル既定はAstra lowを維持し3つのread-only custom agentへ限定routingする", async () => {
  const [configText, workflow, evaluator, ...skillFiles] = await Promise.all([
    read(".codex/config.toml"),
    read("docs/development/codex-development-workflow.md"),
    read("scripts/eval-plan-skills.mjs"),
    ...allSkillNames.flatMap((name) => [
      read(`.agents/skills/${name}/SKILL.md`),
      read(`.agents/skills/${name}/agents/openai.yaml`),
    ]),
  ]);

  const config = parseToml(".codex/config.toml");
  assert.equal(config.model, "gpt-6-astra");
  assert.equal(config.model_reasoning_effort, "low");
  assert.match(configText, /^\[mcp_servers\."openaiDeveloperDocs"\]$/m);
  assert.doesNotMatch(configText, /default_subagent_model|default_subagent_reasoning_effort|max_threads/);

  const agents = config.agents as Record<string, { description: string; config_file: string }>;
  assert.deepEqual(Object.keys(agents).sort(), [
    "independent_reviewer",
    "product_advisor",
    "project_explorer",
  ]);
  const roles = {
    product_advisor: { model: "gpt-5.6-terra", reasoning: "medium" },
    project_explorer: { model: "gpt-5.6-luna", reasoning: "medium" },
    independent_reviewer: { model: "gpt-5.6-terra", reasoning: "high" },
  } as const;
  for (const [name, expected] of Object.entries(roles)) {
    assert.equal(agents[name]?.config_file, `./agents/${name}.toml`);
    assert.ok(agents[name]?.description);
    const agent = parseToml(`.codex/agents/${name}.toml`);
    assert.equal(agent.name, name);
    assert.equal(agent.model, expected.model);
    assert.equal(agent.model_reasoning_effort, expected.reasoning);
    assert.equal(agent.sandbox_mode, "read-only");
    assert.match(String(agent.developer_instructions), /Do not edit files/);
  }

  for (const row of [
    "| `$plan` | `gpt-5.6-sol` | `high` |",
    "| `$implement` | `gpt-5.6-sol` | `high` |",
    "| `$review` | `gpt-6-astra` | `low` |",
    "| `$git-commit-push-pr` | `gpt-5.6-luna` | `medium` |",
    "| `$workflow-retrospective` | `gpt-5.6-terra` | `high` |",
    "| `$workflow-performance-audit` | `gpt-5.6-terra` | `high` |",
  ]) {
    assert.ok(workflow.includes(row), `workflow omitted model recommendation: ${row}`);
  }
  for (const row of [
    "| `$kabeuchi` | `product_advisor` | `gpt-5.6-terra` | `medium` |",
    "| `$plan` | `project_explorer` | `gpt-5.6-luna` | `medium` |",
    "| `$review` | `independent_reviewer` | `gpt-5.6-terra` | `high` |",
  ]) {
    assert.ok(workflow.includes(row), `workflow omitted custom agent routing: ${row}`);
  }
  assert.match(workflow, /親エージェントのproject-local既定は`gpt-6-astra \/ low`/);
  assert.match(workflow, /composerでユーザーが選択したモデルとreasoningを維持する/);
  assert.match(workflow, /spawn時のmodelまたはreasoning overrideを渡さない/);
  assert.match(workflow, /上表以外の一般subagentは.*親taskで選択した設定を継承する/);
  assert.match(workflow, /`xhigh`、`max`、`ultra`は親エージェントのskill別推奨にもcustom agentの固定設定にも使わない/);
  assert.match(workflow, /品質不足が確認された場合だけ/);
  assert.match(workflow, /skillメタデータとproject-local `profiles`ではmodelを指定しない/);
  assert.match(workflow, /`\$implement`、`\$git-commit-push-pr`、`\$workflow-retrospective`、`\$workflow-performance-audit`はsubagentへ委譲せず/);

  const modelSelection = workflow.match(/^## モデル選択\n[\s\S]*?(?=^## )/m)?.[0];
  assert.ok(modelSelection, "workflow is missing the model selection section");
  assert.doesNotMatch(modelSelection, /モデル.{0,20}自動(?:選択|切替)|自動routingを(?:行う|使う)/u);
  assert.doesNotMatch(modelSelection, /週次換算率|削減率/u);

  assert.match(evaluator, /"\.codex", "agents"/);
  assert.match(evaluator, /agents\.project_explorer/);
  assert.match(evaluator, /agents\.independent_reviewer/);
  assert.doesNotMatch(evaluator.match(/"\.codex\/config\.toml",[\s\S]*?\n\s*\);/u)?.[0] ?? "", /mcp_servers/);
  for (const skillFile of skillFiles) {
    assert.doesNotMatch(skillFile, /gpt-5\.|^\s*(?:model|model_reasoning_effort|reasoning_effort)\s*[:=]/m);
  }
});

test("kabeuchiは明示呼び出しで1体のadvisorだけをread-only利用する", async () => {
  const [skill, metadata] = await Promise.all([
    read(".agents/skills/kabeuchi/SKILL.md"),
    read(".agents/skills/kabeuchi/agents/openai.yaml"),
  ]);
  assert.match(skill, /exactly one fresh no-history `product_advisor` custom agent/);
  assert.match(skill, /Do not pass a model or reasoning override/);
  assert.match(skill, /only the current question, confirmed decisions, and necessary evidence/);
  assert.match(skill, /If the custom agent or its configured model is unavailable, stop/);
  assert.match(skill, /Do not silently substitute another agent or model/);
  assert.match(skill, /Validate the advice against the available evidence/);
  assert.match(skill, /Do not edit files, create or revise a plan, implement changes, mutate Git state, or perform external writes/);
  assert.match(metadata, /allow_implicit_invocation: false/);
  assert.doesNotMatch(metadata, /gpt-5\.|model|reasoning/);
});

test("実装・shipping・振り返り・期間監査はcustom agentへ委譲しない", async () => {
  const [implement, shipping, retrospective, performanceAudit] = await Promise.all([
    read(".agents/skills/implement/SKILL.md"),
    read(".agents/skills/git-commit-push-pr/SKILL.md"),
    read(".agents/skills/workflow-retrospective/SKILL.md"),
    read(".agents/skills/workflow-performance-audit/SKILL.md"),
  ]);
  assert.match(implement, /do not delegate implementation to a custom agent/);
  assert.match(shipping, /Do not delegate to a custom agent/);
  assert.match(retrospective, /Do not delegate the audit to a custom agent/);
  assert.match(performanceAudit, /Do not delegate this skill to a custom agent/);
  for (const skill of [implement, shipping, retrospective, performanceAudit]) {
    assert.doesNotMatch(skill, /`product_advisor`|`project_explorer`|`independent_reviewer`/);
  }
});

test("明示的な7 skill構成を保ち廃止skill・lifecycle・旧implementation agentを復活させない", async () => {
  const removed = [
    ".agents/skills/plan-finalize",
    ".agents/skills/plan-critic/SKILL.md",
    ".agents/skills/plan-critic/agents/openai.yaml",
    ".agents/skills/implementation-planner/SKILL.md",
    ".agents/skills/implementation-executor/SKILL.md",
    ".agents/skills/implementation-review/SKILL.md",
    ".agents/skills/final-plan-rewriter/SKILL.md",
    "scripts/validate-plan-file.mjs",
    "scripts/validate-review-data.mjs",
    ".codex/agents/implementer.toml",
    ".codex/agents/plan_author.toml",
  ];
  for (const relative of removed) {
    await assert.rejects(access(path.join(root, relative)), { code: "ENOENT" });
  }
  const [config, workflow, ...skills] = await Promise.all([
    read(".codex/config.toml"),
    read("docs/development/codex-development-workflow.md"),
    ...allSkillNames.map((name) => read(`.agents/skills/${name}/SKILL.md`)),
  ]);
  assert.match(workflow, /custom agentは、壁打ち、広範な読み取り探索、独立reviewという限定されたread-onlyロールだけに使う/);
  assert.match(config, /^\[agents\.product_advisor\]$/m);
  assert.match(config, /^\[agents\.project_explorer\]$/m);
  assert.match(config, /^\[agents\.independent_reviewer\]$/m);
  assert.doesNotMatch(workflow, /\$plan-critic|plan-critic/);
  for (const skill of skills) {
    assert.doesNotMatch(skill, /implementation-(?:planner|executor|review)|final-plan-rewriter|G0[1-6]|gpt-5\./);
  }
});

// Keep structural/entrypoint checks here; observed decisions are exercised by
// the smoke scenario graders and the isolated Git/gh shipping evaluator.
test("goal templateはsmokeの最小設計と5列closureを持つ", async () => {
  const template = await read("plans/template.md");
  assert.deepEqual(template.match(/^# .+$/gm), headings);
  const table = template.split("\n").filter((line) => line.startsWith("|"));
  assert.equal(table.length, 2);
  for (const row of table) assert.equal(row.split("|").length, 7);
  assert.match(template, /^- UI検証方式: 対象外$/mu);
  assert.match(template, /^- 対象外: UI変更なし$/mu);
  assert.doesNotMatch(template, /ui-contract|parity-spec|approval\.json|matrix|schema 6/u);
});

test("active skill reference graphは保存parity資料へ到達しない", async () => {
  const archived = new Set([
    ".agents/skills/plan/references/parity-runner.md",
    ".agents/skills/plan/references/manifest-storage.md",
    ".agents/skills/plan/references/validation-design.md",
    ".agents/skills/plan/references/browser-recovery.md",
  ]);
  const queue = ["AGENTS.md", "docs/development/codex-development-workflow.md", ...["plan", "implement", "review", "git-commit-push-pr"].map((name) => `.agents/skills/${name}/SKILL.md`)];
  const visited = new Set<string>();
  while (queue.length) {
    const relative = queue.pop()!;
    if (visited.has(relative)) continue;
    visited.add(relative);
    assert.ok(!archived.has(relative), `active reference reaches stored parity instructions: ${relative}`);
    const content = await read(relative);
    for (const [, link] of content.matchAll(/\[[^\]]*\]\(([^)]+)\)/gu)) {
      if (/^(?:https?:|codex:|#)/u.test(link) || link.includes("<")) continue;
      const file = link.split("#")[0];
      if (!file.endsWith(".md")) continue;
      const resolved = path.normalize(path.join(path.dirname(relative), file));
      assert.ok(!resolved.startsWith(".."), `reference escapes repository: ${resolved}`);
      queue.push(resolved);
    }
  }
  assert.ok(visited.has(".agents/skills/plan/references/workflow-verification-contract.md"));
  for (const file of archived) assert.match(await read(file), /Historical reference only/u);
});

test("CI guardはローカル資料やarchive履歴を出荷gateにしない", async () => {
  const workflow = await read(".github/workflows/plan-artifact-guard.yml");
  assert.match(workflow, /npm run plans:guard/u);
  assert.doesNotMatch(workflow, /verify-history|verifyPlanTree|plans:cleanup/u);
  const gitignore = await read(".gitignore");
  assert.doesNotMatch(gitignore, /^\/?plans\/\*$/mu);
  assert.notEqual(spawnSync("git", ["check-ignore", "--no-index", "plans/example/goal.md"], { cwd: root }).status, 0);
});

test("workflow scenario登録は全採用要件の行動評価へ接続する", async () => {
  const { scenarios } = await import("../scripts/eval-plan-skills.mjs");
  // The JavaScript registry adds workflow scenarios with Object.assign.
  const registered = scenarios as Record<string, { grade?: unknown; affectedPaths?: string[] }>;
  for (const name of ["smoke-plan-default", "smoke-implement-default", "smoke-implement-prototype-variant", "smoke-unavailable-and-defect", "smoke-legacy-and-review", "ui-design-feedback", "ui-minor-feedback-direct"]) {
    assert.ok(registered[name], `missing scenario: ${name}`);
    assert.equal(typeof registered[name].grade, "function");
    assert.ok(registered[name].affectedPaths?.includes(".agents/skills/implement/"));
  }
});
