import type { SiteLocale } from "@/lib/site-settings";
export type IntakeCopy = { title: string; description: string; displayName: string; nameHelp: string; affiliation: string; select: string; affiliations: string[]; topic: string; topicHelp: string; sharing: string; cancel: string; submit: string; invalid: string };
export const intakeDictionaries: Record<SiteLocale, IntakeCopy> = {
  ja: { title: "相談前にお聞かせください", description: "3項目を入力して、担当者とのビデオ相談へ進みます。すべて必須です。", displayName: "呼び名", nameHelp: "ニックネームでも構いません（40文字以内）。", affiliation: "あなたの立場", select: "選択してください", affiliations: ["受験生", "在学生", "保護者", "その他"], topic: "相談したいこと", topicHelp: "概要を300文字以内で入力してください。", sharing: "入力内容はZoom Contact Centerに送信され、相談の受付に使用されます。", cancel: "戻る", submit: "入力して相談を開始", invalid: "空白だけの入力を避け、各項目を文字数の範囲内で入力してください。" },
  en: { title: "Tell us before we connect", description: "Complete these three required fields to start your video consultation.", displayName: "Preferred name", nameHelp: "A nickname is fine (up to 40 characters).", affiliation: "Your role", select: "Select an option", affiliations: ["Prospective student", "Current student", "Parent or guardian", "Other"], topic: "What would you like to discuss?", topicHelp: "Enter a brief summary, up to 300 characters.", sharing: "Your answers will be sent to Zoom Contact Center for consultation intake.", cancel: "Back", submit: "Start consultation", invalid: "Enter a non-blank response for each field within its character limit." },
  "zh-Hans": { title: "咨询前请告诉我们", description: "填写以下三个必填项后，即可开始视频咨询。", displayName: "称呼", nameHelp: "可以使用昵称（最多40个字符）。", affiliation: "您的身份", select: "请选择", affiliations: ["报考学生", "在校学生", "家长或监护人", "其他"], topic: "想咨询的内容", topicHelp: "请在300个字符以内简要说明。", sharing: "填写的内容将发送至Zoom Contact Center，用于咨询接待。", cancel: "返回", submit: "开始咨询", invalid: "请在字符限制内填写各项，不能仅输入空格。" },
  "zh-Hant": { title: "諮詢前請告訴我們", description: "填寫以下三個必填項後，即可開始視訊諮詢。", displayName: "稱呼", nameHelp: "可以使用暱稱（最多40個字元）。", affiliation: "您的身分", select: "請選擇", affiliations: ["報考學生", "在校學生", "家長或監護人", "其他"], topic: "想諮詢的內容", topicHelp: "請在300個字元以內簡要說明。", sharing: "填寫的內容將傳送至Zoom Contact Center，用於諮詢接待。", cancel: "返回", submit: "開始諮詢", invalid: "請在字元限制內填寫各項，不能僅輸入空格。" },
  ko: { title: "상담 전에 알려 주세요", description: "필수 항목 세 가지를 입력하면 영상 상담을 시작합니다.", displayName: "호칭", nameHelp: "닉네임도 괜찮습니다(최대 40자).", affiliation: "본인의 입장", select: "선택해 주세요", affiliations: ["수험생", "재학생", "학부모 또는 보호자", "기타"], topic: "상담하고 싶은 내용", topicHelp: "300자 이내로 간략하게 입력해 주세요.", sharing: "입력 내용은 상담 접수를 위해 Zoom Contact Center로 전송됩니다.", cancel: "돌아가기", submit: "상담 시작", invalid: "공백만 입력하지 말고 각 항목을 글자 수 제한 내에서 입력해 주세요." },
};
