import type { Locale } from "./dictionaries";
export type MunicipalOutreachDictionary = {
  identityConfirmed: string; title: string; intro: string; name: string; phone: string; district: string; choose: string;
  districts: Record<string, string>; topics: Record<string, string>; notices: string; weekdays: string[]; days: string; start: string; end: string; availability: string;
  boundary: string; consent: string; consentLabel: string; caller: string; confirm: string; back: string; submit: string; submitting: string; accepted: string; acceptedHelp: string; error: string; invalid: string; home: string; link: string;
};
export const municipalOutreachDictionaries: Record<Locale, MunicipalOutreachDictionary> = {
  ja: { identityConfirmed: "本人の氏名を登録内容・確認資料と照合した",
    title: "電話通知の登録", intro: "ご希望の電話連絡を登録できます。職員が登録内容を確認してからご案内します。", name: "氏名", phone: "電話番号", district: "お住まいの地区", choose: "選択してください", districts: { central: "中央地区", east: "東地区", west: "西地区" }, topics: { "elder-watch": "高齢者の定期見守り", "procedure-support": "行政手続きの支援", "service-confirmation": "訪問・サービス利用の確認", "fraud-alert": "特殊詐欺の注意喚起・確認" }, notices: "希望する電話連絡", weekdays: ["日", "月", "火", "水", "木", "金", "土"], days: "希望する曜日", start: "開始時刻", end: "終了時刻", availability: "見守りの希望曜日・時間帯は職員が調整します。", boundary: "この登録だけで給付申請、サービス利用資格、予約は成立しません。電話の回答は健康や安全を保証するものではありません。", consent: "登録内容を、登録確認、選択した電話連絡と必要な職員対応に利用します。内容の変更・停止は担当窓口にお申し出ください。", consentLabel: "利用目的に同意して登録します", caller: "発信元番号と公式窓口は開始前にご案内します。", confirm: "登録内容を確認", back: "入力に戻る", submit: "登録する", submitting: "送信しています", accepted: "登録を受け付けました", acceptedHelp: "職員が本人・電話番号・通知希望を確認してから対象となります。受付だけで電話を発信することはありません。", error: "送信できませんでした。入力内容は保持しています。時間をおいて再度お試しください。", invalid: "必須項目、電話番号、希望日時、同意をご確認ください。", home: "ホームに戻る", link: "電話連絡の希望を登録する",
  },
  en: { identityConfirmed: "Verified the person’s name against registration and supporting records",
    title: "Register for phone notices", intro: "Choose the calls you would like to receive. Staff will review your registration first.", name: "Name", phone: "Phone number", district: "District", choose: "Please select", districts: { central: "Central district", east: "East district", west: "West district" }, topics: { "elder-watch": "Regular check-ins for older residents", "procedure-support": "Help with administrative procedures", "service-confirmation": "Visit and service confirmations", "fraud-alert": "Fraud alerts and check-ins" }, notices: "Requested phone notices", weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"], days: "Preferred days", start: "Start time", end: "End time", availability: "Staff will coordinate your preferred check-in days and times.", boundary: "Registration does not create a benefit application, service eligibility, or booking. Phone answers do not guarantee health or safety.", consent: "We use these details to verify your registration, make the calls you selected, and provide necessary staff follow-up. Contact the responsible office to change or stop notices.", consentLabel: "I agree to these purposes and wish to register", caller: "We will announce the caller number and official contact before service starts.", confirm: "Review registration", back: "Back to form", submit: "Register", submitting: "Submitting", accepted: "Registration received", acceptedHelp: "Staff will verify your identity, phone number, and preferences before you become eligible. Receiving this registration does not place a call.", error: "Could not submit. Your entries have been kept. Please try again later.", invalid: "Check the required fields, phone number, preferred times, and consent.", home: "Return home", link: "Register your phone notice preferences",
  },
  "zh-Hans": { identityConfirmed: "已核对本人姓名与登记及确认资料",
    title: "电话通知登记", intro: "请选择希望接收的电话联系。工作人员将在确认登记内容后提供通知。", name: "姓名", phone: "电话号码", district: "居住地区", choose: "请选择", districts: { central: "中央地区", east: "东部地区", west: "西部地区" }, topics: { "elder-watch": "老年人定期关怀", "procedure-support": "行政手续协助", "service-confirmation": "上门及服务使用确认", "fraud-alert": "诈骗提醒及确认" }, notices: "希望接收的电话联系", weekdays: ["日", "一", "二", "三", "四", "五", "六"], days: "希望联系的星期", start: "开始时间", end: "结束时间", availability: "工作人员将协调您希望的关怀日期和时段。", boundary: "此登记不构成补助申请、服务资格或预约。电话回答不保证健康或安全。", consent: "登记内容将用于登记确认、所选电话联系及必要的工作人员跟进。如需修改或停止，请联系负责窗口。", consentLabel: "我同意上述用途并登记", caller: "服务开始前将公布来电号码及官方联系窗口。", confirm: "确认登记内容", back: "返回填写", submit: "登记", submitting: "正在提交", accepted: "已受理登记", acceptedHelp: "工作人员确认本人、电话号码及通知意愿后才会纳入对象。受理登记不会立即拨打电话。", error: "提交失败。已保留输入内容，请稍后重试。", invalid: "请确认必填项目、电话号码、希望时段及同意事项。", home: "返回首页", link: "登记电话联系意愿",
  },
  "zh-Hant": { identityConfirmed: "已核對本人姓名與登記及確認資料",
    title: "電話通知登記", intro: "請選擇希望接收的電話聯絡。工作人員確認登記內容後才會提供通知。", name: "姓名", phone: "電話號碼", district: "居住地區", choose: "請選擇", districts: { central: "中央地區", east: "東部地區", west: "西部地區" }, topics: { "elder-watch": "長者定期關懷", "procedure-support": "行政手續協助", "service-confirmation": "到訪及服務使用確認", "fraud-alert": "詐騙提醒及確認" }, notices: "希望接收的電話聯絡", weekdays: ["日", "一", "二", "三", "四", "五", "六"], days: "希望聯絡的星期", start: "開始時間", end: "結束時間", availability: "工作人員將協調您希望的關懷日期和時段。", boundary: "此登記不構成補助申請、服務資格或預約。電話回答不保證健康或安全。", consent: "登記內容將用於登記確認、所選電話聯絡及必要的工作人員跟進。如需修改或停止，請聯絡負責窗口。", consentLabel: "我同意上述用途並登記", caller: "服務開始前將公布來電號碼及官方聯絡窗口。", confirm: "確認登記內容", back: "返回填寫", submit: "登記", submitting: "正在提交", accepted: "已受理登記", acceptedHelp: "工作人員確認本人、電話號碼及通知意願後才會納入對象。受理登記不會立即撥打電話。", error: "提交失敗。已保留輸入內容，請稍後重試。", invalid: "請確認必填項目、電話號碼、希望時段及同意事項。", home: "返回首頁", link: "登記電話聯絡意願",
  },
  ko: { identityConfirmed: "등록 내용과 확인 자료로 본인의 성명을 대조했습니다",
    title: "전화 알림 등록", intro: "원하는 전화 연락을 선택해 주세요. 직원이 등록 내용을 확인한 후 안내합니다.", name: "성명", phone: "전화번호", district: "거주 지역", choose: "선택해 주세요", districts: { central: "중앙 지역", east: "동부 지역", west: "서부 지역" }, topics: { "elder-watch": "고령자 정기 안부 확인", "procedure-support": "행정 절차 지원", "service-confirmation": "방문 및 서비스 이용 확인", "fraud-alert": "사기 주의 안내 및 확인" }, notices: "희망하는 전화 연락", weekdays: ["일", "월", "화", "수", "목", "금", "토"], days: "희망 요일", start: "시작 시간", end: "종료 시간", availability: "직원이 희망하는 안부 확인 요일과 시간대를 조정합니다.", boundary: "이 등록만으로 급여 신청, 서비스 이용 자격 또는 예약이 성립하지 않습니다. 전화 응답은 건강이나 안전을 보장하지 않습니다.", consent: "등록 정보는 등록 확인, 선택한 전화 연락 및 필요한 직원 후속 대응에 사용합니다. 변경하거나 중단하려면 담당 창구에 문의해 주세요.", consentLabel: "이용 목적에 동의하고 등록합니다", caller: "발신 번호와 공식 창구는 서비스 시작 전에 안내합니다.", confirm: "등록 내용 확인", back: "입력으로 돌아가기", submit: "등록", submitting: "전송 중", accepted: "등록을 접수했습니다", acceptedHelp: "직원이 본인, 전화번호, 알림 희망 사항을 확인한 후 대상이 됩니다. 접수만으로 전화를 걸지는 않습니다.", error: "전송하지 못했습니다. 입력 내용은 유지됩니다. 잠시 후 다시 시도해 주세요.", invalid: "필수 항목, 전화번호, 희망 시간 및 동의를 확인해 주세요.", home: "홈으로 돌아가기", link: "전화 연락 희망 사항 등록",
  },
};
