import { purposeCampaignDictionaries, type PurposeCampaignDictionary } from "./outreach-purpose-campaigns";
import { defaultGroupsDictionaries, type DefaultGroupsDictionary } from "./outreach-default-groups";
import { groupSyncDictionaries, type GroupSyncDictionary } from "./outreach-group-sync";
import { outreachMemberErrors, type OutreachMemberErrors } from "./outreach-member-errors";
import { outreachZoomImportDictionaries, type OutreachZoomImportDictionary } from "./outreach-zoom-import";
import { outreachCampaignDictionaries, type OutreachCampaignDictionary } from "./outreach-campaign-ui";
import { outreachDispatchDictionaries, type OutreachDispatchDictionary } from "./outreach-dispatch-ui";
import { outreachMessageDictionaries, type OutreachMessageDictionary } from "./outreach-message-ui";
import { campaignSyncDictionaries, type CampaignSyncDictionary } from "./outreach-campaign-sync";
import type { Locale } from "./dictionaries";
export type OutreachCommonDictionary = { purposeCampaigns: PurposeCampaignDictionary; defaultGroups: DefaultGroupsDictionary; tabLabels: Record<"contact-lists" | "campaigns" | "one-time" | "messages", string>; groupSync: GroupSyncDictionary; groupMutationBlocks: Record<"GROUP_IN_USE" | "CAMPAIGN_REFERENCE_UNKNOWN", string>; memberErrors: OutreachMemberErrors; zoomImportUi: OutreachZoomImportDictionary; campaignUi: OutreachCampaignDictionary; dispatchUi: OutreachDispatchDictionary; messageUi: OutreachMessageDictionary; campaignSync: CampaignSyncDictionary; csvPreview: string; groupListName: string; groupMembers: string; groupIndustry: string; groupDeleteTitle: string; groupDeleteHelp: string; groupCreate: string; groupEdit: string; groupName: string; emptyGroupHelp: string; contactDetails: string; contactEdit: string; contactAdd: string; backToContacts: string; registrationStatus: string; setupLabel: string; setupHelp: string; setupPermission: string; returnToOutreach: string; publicationConfirmed: string; replaceMessage: string; rerun: string; noEligibleTargets: string; disasterTopic: string; language: string; legacyHelp: string; stateLabels: Record<string, string>; bindingTitle: string; bindingHelp: string; bindingType: string; bindingId: string; bindingAccount: string; bindingConfirm: string; bindingConflict: string; importStates: Record<string, string>; registrationEnabled: string; registrationHelp: string; registrationClosed: string; departments: Record<string, string>; residentRegister: string; studentRegister: string; csvRegister: string; csvRequirements: string; csvHelp: string; sampleDownload: string; manual: string; deleteContact: string; deleteContactHelp: string; deleteReason: string; registrationSettings: string; reload: string; tabs: string[]; sample: string; sync: string; added: string; select: string; selected: string; department: string; pending: string; active: string; withdrawn: string; unknown: string; audioGate: string; flowGate: string; liveGate: string; retire: string; preview: string; direct: string; savedMessage: string; media: string; flow: string; people: string; groups: string; topic: string; version: string; snapshot: string; staffCases: string; workflow: string; steps: string[]; confirmDiscard: string; discard: string; imported: string; consentRequired: string; source: string; allIndustries: string; memberAdd: string; memberEdit: string; memberDelete: string; memberBoundary: string; link: string; attestation: string; zoomOnly: string; difference: string; linked: string; examples: string };
const csvPreviewLabels: Record<Locale, string> = { ja: "CSV取込前の確認", en: "CSV import preview", "zh-Hans": "CSV导入预览", "zh-Hant": "CSV匯入預覽", ko: "CSV 가져오기 미리보기" };
const groupListLabels: Record<Locale, [string, string, string]> = {
 ja: ["グループ名", "連絡先数", "対応業種"],
 en: ["Group name", "Contact count", "Assigned industry"],
 "zh-Hans": ["群组名称", "联系人数量", "对应行业"],
 "zh-Hant": ["群組名稱", "聯絡人數量", "對應行業"],
 ko: ["그룹 이름", "연락처 수", "연결된 업종"],
};
const groupPageLabels: Record<Locale, [string, string, string, string, string, string]> = {
 ja: ["連絡先グループを作成", "連絡先グループを編集", "管理用名称", "空のグループを作成します。人物や連絡先は自動追加されません。", "グループを削除しますか？", "使用中のキャンペーンがある場合は削除できません。本アプリの人物情報は残ります。"],
 en: ["Create contact group", "Edit contact group", "Administrative name", "An empty group will be created. People and contacts are not added automatically.", "Delete this group?", "Groups used by a campaign cannot be deleted. People registered in this app are retained."],
 "zh-Hans": ["创建联系人群组", "编辑联系人群组", "管理名称", "创建空群组，不会自动添加人员或联系人。", "是否删除此群组？", "营销活动正在使用的群组无法删除。本应用中的人员信息会保留。"],
 "zh-Hant": ["建立聯絡人群組", "編輯聯絡人群組", "管理名稱", "建立空群組，不會自動新增人員或聯絡人。", "是否刪除此群組？", "行銷活動正在使用的群組無法刪除。本應用程式中的人員資訊會保留。"],
 ko: ["연락처 그룹 만들기", "연락처 그룹 편집", "관리용 이름", "빈 그룹을 만듭니다. 사람이나 연락처는 자동으로 추가되지 않습니다.", "이 그룹을 삭제하시겠습니까?", "캠페인에서 사용 중인 그룹은 삭제할 수 없습니다. 이 앱에 등록된 인물 정보는 유지됩니다."],
};
const contactPageLabels: Record<Locale, [string, string, string, string]> = {
  ja: ["連絡先の詳細", "連絡先を編集", "連絡先を追加", "一覧へ戻る"],
  en: ["Contact details", "Edit contact", "Add contact", "Back to list"],
  "zh-Hans": ["联系人详情", "编辑联系人", "添加联系人", "返回列表"],
  "zh-Hant": ["聯絡人詳細資料", "編輯聯絡人", "新增聯絡人", "返回清單"],
  ko: ["연락처 상세", "연락처 편집", "연락처 추가", "목록으로 돌아가기"],
};
const registrationStatusLabels: Record<Locale, string> = { ja: "登録状態", en: "Registration status", "zh-Hans": "登记状态", "zh-Hant": "登記狀態", ko: "등록 상태" };
const setupLabels: Record<Locale, [string, string, string, string]> = {
  ja: ["Zoom API 設定", "オートリーチを利用するには、Zoom API 設定が必要です。", "設定権限を持つ管理者に依頼してください。", "オートリーチへ戻る"],
  en: ["Zoom API settings", "Configure the Zoom API to use outreach.", "Ask an administrator with permission to configure these settings.", "Return to outreach"],
  "zh-Hans": ["Zoom API 设置", "使用外呼服务前，需要配置 Zoom API。", "请联系具有配置权限的管理员。", "返回外呼服务"],
  "zh-Hant": ["Zoom API 設定", "使用外撥服務前，需要設定 Zoom API。", "請聯絡具有設定權限的管理員。", "返回外撥服務"],
  ko: ["Zoom API 설정", "아웃리치를 사용하려면 Zoom API 설정이 필요합니다.", "설정 권한이 있는 관리자에게 요청하세요.", "아웃리치로 돌아가기"],
};
const rows: Record<Locale, string[]> = {
 ja: ["連絡先リスト|連絡先グループ|定型案内|単発案内|メッセージ管理", "サンプルCSV", "同期", "追加済み", "選択", "選択件数", "担当部署", "確認待ち", "有効", "停止", "不明", "音声の生成・試聴は接続契約の確認後に利用できます。", "ZoomでのFlow構成・公開版・本文と音声の対応を確認してください。", "発信設定と接続契約の確認が完了するまで実行できません。", "新規利用を終了", "実行前の確認", "直接入力", "保存したメッセージ", "音声再生", "Flow", "個別の連絡先", "連絡先グループ", "通知種別", "版", "実行時点の記録", "職員の対応一覧", "電話確認と職員対応", "対象者|質問・実行設定|回答結果|職員対応", "未保存の入力を破棄して移動しますか？", "破棄して移動", "取込済み", "取込後に本人・電話番号・通知希望の確認が必要です。", "流入先", "全業種共通", "CRMから所属を追加", "Zoom側の表示名・電話番号を編集", "グループから削除", "所属の編集・削除はZoomのこのグループに反映されます。CRMの人物情報と他グループの所属は保持します。", "CRMの人物に紐付け", "紐付けを確認した根拠", "Zoomのみ・通知同意未確認", "差分あり・要確認", "CRMに紐付け済み", "グループ作成例（任意）"],
 en: ["Contacts|Contact groups|Recurring notices|One-time notices|Messages", "Sample CSV", "Sync", "Already added", "Select", "Selected", "Department", "Pending review", "Active", "Stopped", "Unknown", "Audio generation and playback require a verified connection contract.", "Verify the published Zoom Flow and its text and voice mapping.", "Execution is unavailable until calling settings and connection contracts are verified.", "Retire from new use", "Review before execution", "Enter directly", "Saved message", "Play audio", "Flow", "Individual contacts", "Contact groups", "Notice topic", "Revision", "Execution snapshot", "Staff cases", "Phone checks and staff follow-up", "Targets|Questions and settings|Answers|Staff cases", "Discard unsaved entries and leave?", "Discard and leave", "Imported", "Verify identity, phone ownership, and preferences after importing.", "Source", "All industries", "Add a CRM contact", "Edit Zoom display name and phone", "Remove from group", "Edits and removals affect membership in this Zoom group. CRM records and other group memberships are retained.", "Link to a CRM contact", "Evidence supporting this link", "Zoom only; notice consent unverified", "Difference; review required", "Linked to CRM", "Group examples (optional)"],
 "zh-Hans": ["联系人列表|联系人群组|定期通知|单次通知|消息管理", "CSV示例", "同步", "已添加", "选择", "已选数量", "负责部门", "待确认", "有效", "已停止", "未知", "音频生成及试听需要先验证连接契约。", "请确认Zoom已发布的Flow及其文本与语音对应关系。", "完成呼叫设置和连接契约确认前无法执行。", "停止新用途", "执行前确认", "直接输入", "已保存消息", "播放音频", "Flow", "个别联系人", "联系人群组", "通知类型", "版本", "执行时记录", "工作人员处理列表", "电话确认与工作人员跟进", "对象|问题和执行设置|回答结果|工作人员处理", "放弃未保存的输入并离开？", "放弃并离开", "已导入", "导入后须确认本人、电话所有权及通知意愿。", "来源", "所有行业共通", "添加CRM联系人", "编辑Zoom显示名称和电话", "从群组移除", "编辑和移除仅影响此Zoom群组的成员信息。CRM人物信息及其他群组成员关系将保留。", "关联CRM联系人", "关联确认依据", "仅存在于Zoom，通知同意未确认", "存在差异，需确认", "已关联CRM", "群组创建示例（可选）"],
 "zh-Hant": ["聯絡人清單|聯絡人群組|定期通知|單次通知|訊息管理", "CSV範例", "同步", "已新增", "選擇", "已選數量", "負責部門", "待確認", "有效", "已停止", "未知", "音訊生成及試聽需要先驗證連線契約。", "請確認Zoom已發布的Flow及其文字與語音對應關係。", "完成通話設定及連線契約確認前無法執行。", "停止新用途", "執行前確認", "直接輸入", "已儲存訊息", "播放音訊", "Flow", "個別聯絡人", "聯絡人群組", "通知類型", "版本", "執行時記錄", "工作人員處理清單", "電話確認與工作人員跟進", "對象|問題與執行設定|回答結果|工作人員處理", "放棄未儲存的輸入並離開？", "放棄並離開", "已匯入", "匯入後須確認本人、電話所有權及通知意願。", "來源", "所有行業共通", "新增CRM聯絡人", "編輯Zoom顯示名稱與電話", "從群組移除", "編輯與移除僅影響此Zoom群組的成員資訊。CRM人物資訊及其他群組成員關係將保留。", "連結CRM聯絡人", "連結確認依據", "僅存在於Zoom，通知同意未確認", "存在差異，需確認", "已連結CRM", "群組建立範例（選填）"],
 ko: ["연락처 목록|연락처 그룹|정기 안내|일회성 안내|메시지 관리", "CSV 예제", "동기화", "추가됨", "선택", "선택 수", "담당 부서", "확인 대기", "유효", "중지", "알 수 없음", "음성 생성과 미리 듣기는 연결 계약을 검증한 후 사용할 수 있습니다.", "Zoom에 게시된 Flow와 본문 및 음성의 대응 관계를 확인해 주세요.", "발신 설정과 연결 계약 확인을 마칠 때까지 실행할 수 없습니다.", "신규 사용 종료", "실행 전 확인", "직접 입력", "저장한 메시지", "음성 재생", "Flow", "개별 연락처", "연락처 그룹", "알림 유형", "버전", "실행 시점 기록", "직원 대응 목록", "전화 확인 및 직원 후속 대응", "대상자|질문 및 실행 설정|응답 결과|직원 대응", "저장하지 않은 입력을 버리고 이동할까요?", "버리고 이동", "가져옴", "가져온 후 본인, 전화 소유권 및 알림 희망 사항을 확인해야 합니다.", "유입 경로", "모든 업종 공통", "CRM 연락처 추가", "Zoom 표시 이름과 전화번호 편집", "그룹에서 제거", "편집과 제거는 이 Zoom 그룹의 소속 정보에 반영됩니다. CRM 인물 정보와 다른 그룹의 소속은 유지됩니다.", "CRM 연락처 연결", "연결 확인 근거", "Zoom에만 존재, 알림 동의 미확인", "차이 있음, 확인 필요", "CRM 연결됨", "그룹 생성 예시 (선택)"],
};
const keys = ["tabs", "sample", "sync", "added", "select", "selected", "department", "pending", "active", "withdrawn", "unknown", "audioGate", "flowGate", "liveGate", "retire", "preview", "direct", "savedMessage", "media", "flow", "people", "groups", "topic", "version", "snapshot", "staffCases", "workflow", "steps", "confirmDiscard", "discard", "imported", "consentRequired", "source", "allIndustries", "memberAdd", "memberEdit", "memberDelete", "memberBoundary", "link", "attestation", "zoomOnly", "difference", "linked", "examples"] as const;
const publicationLabels = {"ja": "この番号と案内先を公式サイトで公表済みであり、電話通知の登録ページにも掲載することを確認しました。", "en": "I confirm that this number and office are published on the official website and may be shown on the phone notice registration page.", "zh-Hans": "我确认此号码和窗口已在官方网站公布，并可显示在电话通知登记页面。", "zh-Hant": "我確認此號碼與窗口已在官方網站公布，並可顯示於電話通知登記頁面。", "ko": "이 번호와 안내 창구가 공식 사이트에 공개되어 있으며 전화 알림 등록 페이지에도 표시할 수 있음을 확인했습니다."} as const;
const dispatchLabels = {"ja": ["入力中の本文と音声を保存済みメッセージに置き換えますか？", "新しい案内として再作成", "発信できる対象者がいません。選択内容と除外理由を確認してください。", "防災無線通知", "言語"], "en": ["Replace the current text and voice with this saved message?", "Create a new notice from this record", "No eligible recipients. Review your selection and exclusion reasons.", "Disaster radio notices", "Language"], "zh-Hans": ["将当前文本和语音替换为已保存消息？", "根据此记录创建新通知", "没有符合条件的对象。请检查选择和排除原因。", "防灾广播通知", "语言"], "zh-Hant": ["將目前文字與語音替換為已儲存訊息？", "根據此記錄建立新通知", "沒有符合條件的對象。請檢查選擇與排除原因。", "防災廣播通知", "語言"], "ko": ["현재 본문과 음성을 저장한 메시지로 바꿀까요?", "이 기록으로 새 안내 만들기", "발신 가능한 대상자가 없습니다. 선택과 제외 사유를 확인해 주세요.", "방재 방송 알림", "언어"]} as const;
const legacyLabels = {"ja": "旧防災通知の登録情報です。この同意を新しい4種類の電話通知へ転用しません。", "en": "This is an existing disaster notice registration. Its consent does not apply to the four new phone notice topics.", "zh-Hans": "这是原有防灾通知登记信息。此同意不适用于四种新的电话通知。", "zh-Hant": "這是原有防災通知登記資訊。此同意不適用於四種新的電話通知。", "ko": "기존 방재 알림 등록 정보입니다. 이 동의는 새로운 네 가지 전화 알림에 적용되지 않습니다."} as const;
const stateKeys = ["DRAFT", "READY", "RUNNING", "PAUSED", "COMPLETED", "NOT_RUNNING", "UNKNOWN", "VALIDATING", "PREPARING", "EXECUTION_REQUESTED", "CANCELLED", "FAILED", "QUEUED", "NO_ANSWER", "BUSY", "REJECTED", "ANSWERED", "UNVERIFIED", "SELF_ATTESTED", "VERIFIED", "OTHER_PERSON", "VOICEMAIL", "NONE", "CLEAR", "AMBIGUOUS", "ERROR", "CONFIRMED", "UNCONFIRMED", "PENDING", "PHONE_CONFIRMATION_COMPLETE", "CONCERN", "CALLBACK_REQUESTED", "CONSULTATION_REQUESTED", "RESEND_REQUESTED", "COMPLETION_REPORTED", "SUBMISSION_PLANNED", "CHANGE_REQUESTED", "CANCELLATION_REQUESTED", "SIMILAR_CALL_REPORTED", "WITHDRAWN", "PENDING_REVIEW", "DUPLICATE_PHONE", "ZOOM_ONLY", "OUT_OF_SCOPE", "TOPIC_NOT_REQUESTED"];
const stateRows = {"ja": "下書き|実行準備完了|実行中|一時停止|完了|稼働時間外・非稼働|不明|確認中|準備中|実行要求済み|取消済み|失敗|発信待ち|未応答|通話中|着信拒否|接続済み|未確認|本人の申告のみ|確認済み|別の人が応答|留守番電話|未取得|明瞭|不明瞭|エラー|確認済み|未確認|確認待ち|電話確認完了|気になることがある|折り返し希望|相談希望|案内の再送希望|本人が完了を申告|提出予定|変更希望|中止希望|似た電話を受けた|通知停止|登録確認待ち|電話番号の重複|Zoomのみ|権限範囲外|通知希望なし", "en": "Draft|Ready|Running|Paused|Completed|Not running|Unknown|Validating|Preparing|Execution requested|Cancelled|Failed|Queued|No answer|Busy|Rejected|Connected|Unverified|Self-attested only|Verified|Answered by someone else|Voicemail|Not received|Clear|Ambiguous|Error|Confirmed|Unconfirmed|Pending|Phone confirmation complete|Concern reported|Callback requested|Consultation requested|Resend requested|Completion self-reported|Submission planned|Change requested|Cancellation requested|Similar call reported|Notices stopped|Registration pending review|Duplicate phone|Zoom only|Outside permitted scope|Topic not requested", "zh-Hans": "草稿|准备完成|运行中|已暂停|已完成|未运行|未知|确认中|准备中|已请求执行|已取消|失败|等待呼叫|未接听|忙线|拒接|已接通|未验证|仅本人声明|已验证|他人接听|语音信箱|未获取|清晰|不明确|错误|已确认|未确认|待确认|电话确认完成|报告担忧|希望回电|希望咨询|希望重发|本人声明已完成|计划提交|请求变更|请求取消|报告类似电话|停止通知|登记待确认|电话号码重复|仅Zoom|权限范围外|未选择此通知", "zh-Hant": "草稿|準備完成|執行中|已暫停|已完成|未執行|未知|確認中|準備中|已請求執行|已取消|失敗|等待通話|未接聽|忙線|拒接|已接通|未驗證|僅本人聲明|已驗證|他人接聽|語音信箱|未取得|清晰|不明確|錯誤|已確認|未確認|待確認|電話確認完成|回報擔憂|希望回電|希望諮詢|希望重送|本人聲明已完成|計畫提交|請求變更|請求取消|回報類似電話|停止通知|登記待確認|電話號碼重複|僅Zoom|權限範圍外|未選擇此通知", "ko": "초안|준비 완료|실행 중|일시 중지|완료|비가동|알 수 없음|확인 중|준비 중|실행 요청됨|취소됨|실패|발신 대기|무응답|통화 중|수신 거부|연결됨|미검증|본인 진술만 있음|검증됨|다른 사람 응답|음성 사서함|미수신|명확|불명확|오류|확인됨|미확인|확인 대기|전화 확인 완료|우려 사항 있음|회신 희망|상담 희망|재발송 희망|본인 완료 신고|제출 예정|변경 희망|중지 희망|비슷한 전화 신고|알림 중지|등록 확인 대기|전화번호 중복|Zoom에만 존재|권한 범위 밖|알림 희망 없음"} as const;
const bindingLabels = {"ja": ["リソース対応設定", "ZoomにあるIDを確認して、現在の業種・部署・通知種別との対応を保存します。Zoom上の設定や人物・通知同意は変更しません。", "リソースの種類", "ZoomリソースID", "Zoomアカウント", "対応内容を確認", "対応やZoomの状態が変わりました。再取得して確認してください。"], "en": ["Resource mappings", "Verify an existing Zoom ID and map it to the current industry, department, and notice topic. Zoom configuration, contact records, and consent remain unchanged.", "Resource type", "Zoom resource ID", "Zoom account", "Review mapping", "The mapping or Zoom state changed. Reload and review."], "zh-Hans": ["资源对应设置", "确认现有Zoom ID并保存与当前行业、部门及通知类型的对应关系。不修改Zoom配置、人物资料或通知同意。", "资源类型", "Zoom资源ID", "Zoom账户", "确认对应内容", "对应关系或Zoom状态已更改，请重新获取并确认。"], "zh-Hant": ["資源對應設定", "確認既有Zoom ID並儲存與目前行業、部門及通知類型的對應關係。不修改Zoom設定、人物資料或通知同意。", "資源類型", "Zoom資源ID", "Zoom帳戶", "確認對應內容", "對應關係或Zoom狀態已變更，請重新取得並確認。"], "ko": ["리소스 매핑 설정", "기존 Zoom ID를 확인하고 현재 업종, 부서 및 알림 유형과의 관계를 저장합니다. Zoom 설정, 인물 정보 및 알림 동의는 변경하지 않습니다.", "리소스 유형", "Zoom 리소스 ID", "Zoom 계정", "매핑 내용 확인", "매핑이나 Zoom 상태가 변경되었습니다. 새로고침 후 확인해 주세요."]} as const;
const bindingKeys = ["bindingTitle", "bindingHelp", "bindingType", "bindingId", "bindingAccount", "bindingConfirm", "bindingConflict"] as const;
const importStateLabels = {"ja": ["追加予定", "ファイル内重複", "入力エラー", "既存一致・確認が必要", "取込済み", "取込失敗・再試行", "取込中", "有効期限切れ"], "en": ["Will be added", "Duplicate in file", "Invalid input", "Existing match; review required", "Imported", "Import failed; retry", "Importing", "Expired"], "zh-Hans": ["待添加", "文件内重复", "输入错误", "已有匹配，需确认", "已导入", "导入失败，请重试", "导入中", "已过期"], "zh-Hant": ["待新增", "檔案內重複", "輸入錯誤", "既有符合項目，需確認", "已匯入", "匯入失敗，請重試", "匯入中", "已過期"], "ko": ["추가 예정", "파일 내 중복", "입력 오류", "기존 일치, 확인 필요", "가져옴", "가져오기 실패, 재시도", "가져오는 중", "유효 기간 만료"]} as const;
const importStateKeys = ["NEW", "DUPLICATE", "INVALID", "MATCH", "IMPORTED", "FAILED", "IMPORTING", "EXPIRED"];
const receptionLabels = {"ja": ["公開登録を受け付ける", "公開登録の受付を管理します。登録後は本人と連絡先を確認してから通知を有効にします。受付を停止しても登録済み情報は保持します。", "現在、電話通知の新規登録を停止しています。お問い合わせは公式サイトの窓口へご連絡ください。"], "en": ["Accept public registrations", "Manage public registration reception. Verify identity and phone ownership before enabling notices. Existing registrations remain when reception is closed.", "New phone notice registrations are currently closed. Please contact the office listed on the official website."], "zh-Hans": ["接受公开登记", "管理公开登记受理。登记后须确认本人和电话所有权才可启用通知。停止受理后保留已有信息。", "目前暂停接受电话通知新登记。请联系官方网站公布的窗口。"], "zh-Hant": ["接受公開登記", "管理公開登記受理。登記後須確認本人與電話所有權才可啟用通知。停止受理後保留既有資訊。", "目前暫停接受電話通知新登記。請聯絡官方網站公布的窗口。"], "ko": ["공개 등록 접수", "공개 등록 접수를 관리합니다. 등록 후 본인과 전화 소유권을 확인한 뒤 알림을 활성화합니다. 접수를 중지해도 기존 등록 정보는 유지됩니다.", "현재 전화 알림 신규 등록이 중지되어 있습니다. 공식 사이트의 창구로 문의해 주세요."]} as const;
const contactLabels = {"ja": ["住民登録", "学生登録", "CSV一括登録", "CSVファイルの要件", "UTF-8（BOM対応）、1MiB・1,000件まで。氏名と電話番号は必須、大学では7桁の学籍番号も必須です。電話番号と学籍番号は先頭の0を残す文字列として保存してください。", "CSVサンプルをダウンロード", "個別", "連絡先を削除", "この連絡先を新しい通知の対象から外します。過去の案内履歴とZoomの所属は保持します。", "削除理由", "登録設定", "再取得"], "en": ["Register resident", "Register student", "Import CSV", "CSV file requirements", "UTF-8 with optional BOM, up to 1 MiB and 1,000 rows. Name and phone are required; university contacts also require a 7-digit student number. Keep phone and student numbers as text to preserve leading zeros.", "Download sample CSV", "Manual", "Delete contact", "Exclude this contact from new notices. Past notice records and Zoom memberships are retained.", "Reason for deletion", "Registration settings", "Refresh"], "zh-Hans": ["登记居民", "登记学生", "CSV批量导入", "CSV文件要求", "UTF-8（支持BOM），最大1MiB、1,000行。姓名及电话必填，大学联系人还需填写7位学号。请将电话和学号保存为文本以保留开头的0。", "下载CSV示例", "手动", "删除联系人", "将此联系人排除在新通知对象之外。保留过去的通知记录及Zoom成员关系。", "删除原因", "登记设置", "刷新"], "zh-Hant": ["登記居民", "登記學生", "CSV批次匯入", "CSV檔案要求", "UTF-8（支援BOM），最大1MiB、1,000列。姓名及電話必填，大學聯絡人還需填寫7位學號。請將電話與學號儲存為文字以保留開頭的0。", "下載CSV範例", "手動", "刪除聯絡人", "將此聯絡人排除在新通知對象之外。保留過去的通知記錄及Zoom成員關係。", "刪除原因", "登記設定", "重新取得"], "ko": ["주민 등록", "학생 등록", "CSV 일괄 등록", "CSV 파일 요건", "UTF-8 (BOM 지원), 최대 1MiB 및 1,000행입니다. 이름과 전화번호는 필수이며 대학 연락처는 7자리 학번도 필수입니다. 전화번호와 학번은 앞자리 0을 유지하도록 텍스트로 저장하세요.", "CSV 예제 다운로드", "수동", "연락처 삭제", "이 연락처를 새 알림 대상에서 제외합니다. 과거 안내 기록과 Zoom 소속은 유지됩니다.", "삭제 사유", "등록 설정", "새로고침"]} as const;
const contactLabelKeys = ["residentRegister", "studentRegister", "csvRegister", "csvRequirements", "csvHelp", "sampleDownload", "manual", "deleteContact", "deleteContactHelp", "deleteReason", "registrationSettings", "reload"] as const;
const departmentKeys = ["resident-support", "welfare", "procedures", "services", "community-safety", "admissions", "student-affairs", "exam-office", "academic-affairs", "facilities", "international", "student-support"];
const departmentNames: Record<Locale, string[]> = {
 ja: ["住民窓口", "福祉", "手続き支援", "サービス担当", "地域安全", "入試課", "学生課", "試験事務", "教務課", "施設管理", "国際交流", "学生支援"],
 en: ["Resident Services", "Welfare", "Procedure Support", "Service Office", "Community Safety", "Admissions", "Student Affairs", "Examination Office", "Academic Affairs", "Facilities", "International Office", "Student Support"],
 "zh-Hans": ["居民窗口", "福利", "手续支持", "服务部门", "社区安全", "入学事务处", "学生事务处", "考试事务处", "教务处", "设施管理", "国际交流", "学生支持"],
 "zh-Hant": ["居民窗口", "福利", "手續支援", "服務部門", "社區安全", "入學事務處", "學生事務處", "考試事務處", "教務處", "設施管理", "國際交流", "學生支援"],
 ko: ["주민 창구", "복지", "절차 지원", "서비스 담당", "지역 안전", "입학과", "학생과", "시험 사무", "교무과", "시설 관리", "국제 교류", "학생 지원"],
};
const groupMutationBlocks: Record<Locale, OutreachCommonDictionary["groupMutationBlocks"]> = {
  "ja": {
    "GROUP_IN_USE": "実行中・常時稼働中、または状態未確認の案内が使用しています。グループとZoom上の所属は変更できません。案内を一時停止し、状態を確認してから再取得してください。",
    "CAMPAIGN_REFERENCE_UNKNOWN": "案内の利用状態を確認できないため、グループとZoom上の所属は変更できません。管理者に状態確認を依頼し、確認後に再取得してください。"
  },
  "en": {
    "GROUP_IN_USE": "A running, always-on, or unverified notice uses this group. The group and its Zoom memberships cannot be changed. Pause the notice, verify its status, then reload.",
    "CAMPAIGN_REFERENCE_UNKNOWN": "The notice usage status is unknown, so the group and its Zoom memberships cannot be changed. Ask an administrator to verify the status, then reload."
  },
  "zh-Hans": {
    "GROUP_IN_USE": "正在执行、持续运行或状态未确认的通知正在使用此群组。无法更改群组及Zoom成员关系。请暂停通知并确认状态后重新获取。",
    "CAMPAIGN_REFERENCE_UNKNOWN": "无法确认通知的使用状态，因此无法更改群组及Zoom成员关系。请管理员确认状态后重新获取。"
  },
  "zh-Hant": {
    "GROUP_IN_USE": "正在執行、持續運作或狀態未確認的通知正在使用此群組。無法變更群組及Zoom成員關係。請暫停通知並確認狀態後重新取得。",
    "CAMPAIGN_REFERENCE_UNKNOWN": "無法確認通知的使用狀態，因此無法變更群組及Zoom成員關係。請管理員確認狀態後重新取得。"
  },
  "ko": {
    "GROUP_IN_USE": "실행 중이거나 상시 실행 중이거나 상태가 확인되지 않은 안내가 이 그룹을 사용하고 있습니다. 그룹과 Zoom 소속을 변경할 수 없습니다. 안내를 일시 정지하고 상태를 확인한 후 다시 불러오세요.",
    "CAMPAIGN_REFERENCE_UNKNOWN": "안내의 사용 상태를 확인할 수 없어 그룹과 Zoom 소속을 변경할 수 없습니다. 관리자에게 상태 확인을 요청하고 확인 후 다시 불러오세요."
  }
};
export const outreachCommonDictionaries = Object.fromEntries(Object.entries(rows).map(([locale, values]) => {
 if (values.length !== keys.length) throw new Error(`Invalid outreach dictionary: ${locale}`);
 return [locale, { purposeCampaigns: purposeCampaignDictionaries[locale as Locale], defaultGroups: defaultGroupsDictionaries[locale as Locale], tabLabels: Object.fromEntries(["contact-lists", "campaigns", "one-time", "messages"].map((key, i) => [key, values[0].split("|").slice(1)[i]])), groupSync: groupSyncDictionaries[locale as Locale], groupMutationBlocks: groupMutationBlocks[locale as Locale], memberErrors: outreachMemberErrors[locale as Locale], zoomImportUi: outreachZoomImportDictionaries[locale as Locale], campaignUi: outreachCampaignDictionaries[locale as Locale], dispatchUi: outreachDispatchDictionaries[locale as Locale], messageUi: outreachMessageDictionaries[locale as Locale], campaignSync: campaignSyncDictionaries[locale as Locale], csvPreview: csvPreviewLabels[locale as Locale], ...Object.fromEntries(["groupListName", "groupMembers", "groupIndustry"].map((key, index) => [key, groupListLabels[locale as Locale][index]])), ...Object.fromEntries(["groupCreate", "groupEdit", "groupName", "emptyGroupHelp", "groupDeleteTitle", "groupDeleteHelp"].map((key, index) => [key, groupPageLabels[locale as Locale][index]])), ...Object.fromEntries(["contactDetails", "contactEdit", "contactAdd", "backToContacts"].map((key, index) => [key, contactPageLabels[locale as Locale][index]])), registrationStatus: registrationStatusLabels[locale as Locale], ...Object.fromEntries(["setupLabel", "setupHelp", "setupPermission", "returnToOutreach"].map((key, index) => [key, setupLabels[locale as Locale][index]])), publicationConfirmed: publicationLabels[locale as Locale], ...Object.fromEntries(["replaceMessage", "rerun", "noEligibleTargets", "disasterTopic", "language"].map((key, index) => [key, dispatchLabels[locale as Locale][index]])), legacyHelp: legacyLabels[locale as Locale], stateLabels: Object.fromEntries(stateKeys.map((key, index) => [key, stateRows[locale as Locale].split("|")[index]])), ...Object.fromEntries(bindingKeys.map((key, index) => [key, bindingLabels[locale as Locale][index]])), importStates: Object.fromEntries(importStateKeys.map((key, index) => [key, importStateLabels[locale as Locale][index]])), registrationEnabled: receptionLabels[locale as Locale][0], registrationHelp: receptionLabels[locale as Locale][1], registrationClosed: receptionLabels[locale as Locale][2], ...Object.fromEntries(contactLabelKeys.map((key, index) => [key, contactLabels[locale as Locale][index]])), ...Object.fromEntries(keys.map((key, index) => [key, key === "tabs" ? values[index].split("|").slice(1) : key === "steps" ? values[index].split("|") : values[index]])), departments: Object.fromEntries(departmentKeys.map((key, index) => [key, departmentNames[locale as Locale][index]])) }];
})) as Record<Locale, OutreachCommonDictionary>;
