import type { Locale } from "./dictionaries";
import type { MemberSyncStatus } from "@/lib/zaad/default-groups";

const keys = ["defaultLabel", "listId", "configure", "configureTitle", "configureHelp", "missing", "missingHelp", "listHelp", "unsynced", "total", "bulk", "complete", "partial", "source", "site", "boundary", "back", "providerFailure", "manageContacts", "rebindHelp", "reconcile", "reconcileHelp", "contactId", "resume", "waiting", "unknownHelp", "importFromZoom", "radioName", "rebindCount", "candidateSelect", "candidateEmpty", "candidateLoading", "candidateFailure", "candidateRefresh", "candidateSaved", "assignedDefault", "otherIndustry", "internalResource", "currentMissing", "currentAccountChanged", "currentConflict", "candidateTransientFailure", "update", "syncStatusHelp"] as const;
export type DefaultGroupsDictionary = Record<typeof keys[number], string> & { updateShort: string; statuses: Record<MemberSyncStatus, string> };
const rows: Record<Locale, string[]> = {
 ja: ["デフォルト", "連絡先リストID", "IDを設定", "Zoom連絡先リストを選択", "Zoom Contact Centerのキャンペーン用連絡先リストに関連付けます。保存後に同期できます。", "未設定", "Zoom連絡先リストIDが未設定です。設定後に同期できます。", "希望項目ごとにZoom連絡先リストを選択します。サイトの登録者は選択したグループへ追加されます。", "未同期 {count}", "全体 {count}人", "一括同期", "{count}人の同期が完了しました。", "同期完了 {synced}人 / 未完了 {failed}人。各行の状態を確認してください。", "登録元", "サイト", "同期完了は、職員による確認や配信開始を意味しません。", "連絡先グループに戻る", "Zoomから取得できません。件数は未確定です。", "登録・連絡先管理", "リストを変更すると所属ユーザーの再同期が必要です。旧リストの連絡先は残ります。変更先を確認してください。", "関連付けを確認", "Zoom側の連絡先を確認して選択してください。電話番号だけでは同一人物と判定しません。", "Zoom連絡先ID", "同期を再開", "配信中のため同期待ち", "送信結果または変更内容の確認が必要です。関連付けを確認してから再試行してください。", "Zoomから取り込む", "防災無線", "再同期対象：{count}人", "連絡先リストを選択", "選択できる連絡先リストがありません", "連絡先リストを取得しています…", "取得できませんでした。\n再取得ボタンで再試行してください。", "連絡先リストを再取得", "連絡先リストを保存しました。", "別の既定グループに割当済み", "他の業種に割当済み", "内部配信用リスト", "現在のリストは削除されています。有効な候補を選択してください。", "設定時とZoomアカウントが異なります。有効な候補を選択してください。", "現在のリストは割当が競合しています。有効な候補を選択してください。", "Zoom APIとの通信が一時的に不安定です。\n再取得ボタンで再試行するか、しばらく待ってから再試行してください。", "IDを更新", "同期状態について"],
 en: ["Default", "Contact list ID", "Set ID", "Select a Zoom contact list", "Link a Zoom Contact Center campaign contact list. You can sync after saving.", "Not configured", "Set the Zoom contact list ID before syncing.", "Set a Zoom contact list ID for each topic. Website registrations join their selected groups.", "Unsynced {count}", "Total {count}", "Sync all", "Synced {count} people.", "Synced {synced} / Incomplete {failed}. Check each row.", "Source", "Website", "Sync completion does not approve registration or start calls.", "Back to contact groups", "Could not retrieve Zoom contacts. Totals are unavailable.", "Registrations and contacts", "Changing lists requires members to be synced again. Contacts remain in the old list. Confirm the destination.", "Confirm link", "Check and select the Zoom contact. Phone numbers alone do not establish identity.", "Zoom contact ID", "Resume sync", "Waiting while campaign is running", "The write result or changed data needs review. Confirm the link before retrying.", "Import from Zoom", "Disaster radio", "Members to resync: {count}", "Select a contact list", "No contact lists available", "Loading contact lists…", "Could not load contact lists.\nUse the refresh button to retry.", "Refresh contact lists", "Contact list saved.", "Assigned to another default group", "Assigned to another industry", "Internal delivery list", "The current list was deleted. Select an available list.", "The Zoom account has changed. Select an available list.", "The current list has an assignment conflict. Select an available list.", "Communication with the Zoom API is temporarily unstable.\nUse the refresh button or wait a while before retrying.", "Update ID", "About sync status"],
 "zh-Hans": ["默认", "联系人列表ID", "设置ID", "选择Zoom联系人列表", "关联Zoom Contact Center营销活动联系人列表，保存后可同步。", "未设置", "请先选择Zoom联系人列表再同步。", "为每个选项选择Zoom联系人列表。网站登记者将加入其选择的群组。", "未同步 {count}", "共 {count}人", "批量同步", "已同步{count}人。", "已同步{synced}人 / 未完成{failed}人。请检查各行状态。", "登记来源", "网站", "同步完成不代表工作人员已确认或开始拨打电话。", "返回联系人群组", "无法获取Zoom联系人，总数尚未确定。", "登记与联系人管理", "更改列表后需要重新同步成员。旧列表中的联系人将保留，请确认目标列表。", "确认关联", "请检查并选择Zoom联系人。不能仅凭电话号码判断身份。", "Zoom联系人ID", "继续同步", "活动运行中，等待同步", "请确认发送结果或变更内容。确认关联后重试。", "从Zoom导入", "防灾广播", "需要重新同步：{count}人", "选择联系人列表", "没有可选择的联系人列表", "正在获取联系人列表…", "无法获取联系人列表。\n请使用刷新按钮重试。", "刷新联系人列表", "已保存联系人列表。", "已分配给其他默认群组", "已分配给其他行业", "内部发送列表", "当前列表已被删除。请选择可用列表。", "Zoom账户已更改。请选择可用列表。", "当前列表存在分配冲突。请选择可用列表。", "与Zoom API的通信暂时不稳定。\n请使用刷新按钮重试，或稍后再试。", "更新ID", "关于同步状态"],
 "zh-Hant": ["預設", "聯絡人清單ID", "設定ID", "選擇Zoom聯絡人清單", "連結Zoom Contact Center行銷活動聯絡人清單，儲存後可同步。", "未設定", "請先選擇Zoom聯絡人清單再同步。", "為每個選項選擇Zoom聯絡人清單。網站登記者將加入其選擇的群組。", "未同步 {count}", "共 {count}人", "批次同步", "已同步{count}人。", "已同步{synced}人 / 未完成{failed}人。請檢查各列狀態。", "登記來源", "網站", "同步完成不代表工作人員已確認或開始撥打電話。", "返回聯絡人群組", "無法取得Zoom聯絡人，總數尚未確定。", "登記與聯絡人管理", "變更清單後需要重新同步成員。舊清單中的聯絡人將保留，請確認目標清單。", "確認連結", "請檢查並選擇Zoom聯絡人。不能僅憑電話號碼判斷身分。", "Zoom聯絡人ID", "繼續同步", "活動執行中，等待同步", "請確認傳送結果或變更內容。確認連結後重試。", "從Zoom匯入", "防災廣播", "需要重新同步：{count}人", "選擇聯絡人清單", "沒有可選擇的聯絡人清單", "正在取得聯絡人清單…", "無法取得聯絡人清單。\n請使用重新整理按鈕重試。", "重新整理聯絡人清單", "已儲存聯絡人清單。", "已分配給其他預設群組", "已分配給其他業種", "內部傳送清單", "目前清單已被刪除。請選擇可用清單。", "Zoom帳戶已變更。請選擇可用清單。", "目前清單存在分配衝突。請選擇可用清單。", "與Zoom API的通訊暫時不穩定。\n請使用重新整理按鈕重試，或稍後再試。", "更新ID", "關於同步狀態"],
 ko: ["기본", "연락처 목록 ID", "ID 설정", "Zoom 연락처 목록 선택", "Zoom Contact Center 캠페인 연락처 목록을 연결합니다. 저장 후 동기화할 수 있습니다.", "미설정", "동기화 전에 Zoom 연락처 목록 ID를 설정해 주세요.", "항목별로 Zoom 연락처 목록 ID를 설정합니다. 웹사이트 등록자는 선택한 그룹에 추가됩니다.", "미동기화 {count}", "전체 {count}명", "일괄 동기화", "{count}명을 동기화했습니다.", "동기화 {synced}명 / 미완료 {failed}명. 각 행의 상태를 확인하세요.", "등록 경로", "웹사이트", "동기화 완료는 직원 확인이나 발신 시작을 의미하지 않습니다.", "연락처 그룹으로 돌아가기", "Zoom 연락처를 가져올 수 없습니다. 전체 수는 미확정입니다.", "등록 및 연락처 관리", "목록을 변경하면 구성원을 다시 동기화해야 합니다. 기존 목록의 연락처는 유지됩니다. 대상을 확인하세요.", "연결 확인", "Zoom 연락처를 확인하고 선택하세요. 전화번호만으로 동일인으로 판단하지 않습니다.", "Zoom 연락처 ID", "동기화 재개", "캠페인 실행 중 동기화 대기", "전송 결과나 변경 내용을 확인해야 합니다. 연결 확인 후 다시 시도하세요.", "Zoom에서 가져오기", "재난 방송", "재동기화 대상: {count}명", "연락처 목록 선택", "선택할 수 있는 연락처 목록이 없습니다", "연락처 목록을 가져오는 중…", "목록을 가져오지 못했습니다.\n새로고침 버튼으로 다시 시도하세요.", "연락처 목록 새로고침", "연락처 목록을 저장했습니다.", "다른 기본 그룹에 할당됨", "다른 업종에 할당됨", "내부 발송 목록", "현재 목록이 삭제되었습니다. 사용 가능한 목록을 선택하세요.", "Zoom 계정이 변경되었습니다. 사용 가능한 목록을 선택하세요.", "현재 목록의 할당이 충돌합니다. 사용 가능한 목록을 선택하세요.", "Zoom API와의 통신이 일시적으로 불안정합니다.\n새로고침 버튼으로 다시 시도하거나 잠시 후 다시 시도하세요.", "ID 업데이트", "동기화 상태 안내"],
};
const statuses: Record<Locale, string[]> = {
 ja: ["登録済み", "同期完了", "未同期", "同期失敗", "同期中", "要確認", "要確認", "停止"],
 en: ["Registered", "Synced", "Unsynced", "Sync failed", "Syncing", "Review required", "Review required", "Withdrawn"],
 "zh-Hans": ["已登记", "同步完成", "未同步", "同步失败", "同步中", "需确认", "需确认", "已停止"],
 "zh-Hant": ["已登記", "同步完成", "未同步", "同步失敗", "同步中", "需確認", "需確認", "已停止"],
 ko: ["등록됨", "동기화 완료", "미동기화", "동기화 실패", "동기화 중", "확인 필요", "확인 필요", "중지"],
};
const statusKeys: MemberSyncStatus[] = ["REGISTERED", "SYNCED", "PENDING", "FAILED", "SYNCING", "UNKNOWN", "DIFFERENCE", "WITHDRAWN"];
export const defaultGroupsDictionaries = Object.fromEntries(Object.entries(rows).map(([locale, values]) => [locale, { updateShort: ({ja:"更新",en:"Update","zh-Hans":"更新","zh-Hant":"更新",ko:"업데이트"} as Record<Locale,string>)[locale as Locale], ...Object.fromEntries(keys.map((key, i) => [key, values[i]])), statuses: Object.fromEntries(statusKeys.map((key, i) => [key, statuses[locale as Locale][i]])) }])) as Record<Locale, DefaultGroupsDictionary>;
