import type { Locale } from "./dictionaries";
export type OutreachZoomImportDictionary = {
  groupTitle: string; singleTitle: string; help: string; studentHelp: string; contents: string;
  addPending: string; partial: string; changed: string; saved: string; incomplete: string;
};
export const outreachZoomImportDictionaries: Record<Locale, OutreachZoomImportDictionary> = {
  ja: { groupTitle: "グループを一括同期", singleTitle: "本アプリに追加", help: "Zoomの所属連絡先を本アプリの連絡先リストへ取り込みます。既存の人物情報は上書きせず、未登録の連絡先を確認待ちで追加します。同期は発信や通知同意の代わりにはなりません。", studentHelp: "学生は取込後に学籍番号を補い、本人・電話番号・通知同意を確認してください。", contents: "取込内容", addPending: "確認待ちで追加", partial: "一部の連絡先を追加できませんでした。行ごとの結果を確認し、失敗した行を再試行してください。", changed: "取込前の確認後に対象が変わったか、確認の有効期限が切れました。再取得して内容を確認してください。", saved: "選択した連絡先を確認待ちで追加しました。", incomplete: "情報不足・確認が必要" },
  en: { groupTitle: "Sync group contacts", singleTitle: "Add to this app", help: "Import Zoom group contacts into this app. Existing people are not overwritten; new contacts are added for review. Syncing does not place calls or establish notification consent.", studentHelp: "After importing students, add their student numbers and verify identity, phone numbers, and notification consent.", contents: "Import outcome", addPending: "Add for review", partial: "Some contacts could not be added. Review each outcome and retry the failed rows.", changed: "The targets changed or the preview expired. Refresh and review the current information.", saved: "Selected contacts were added for review.", incomplete: "Missing information; review required" },
  "zh-Hans": { groupTitle: "批量同步群组联系人", singleTitle: "添加到本应用", help: "将Zoom群组联系人导入本应用。不覆盖现有人员信息，新增联系人将处于待确认状态。同步不会发起呼叫，也不代表已获得通知同意。", studentHelp: "导入学生后，请补充学号并确认本人身份、电话号码和通知同意。", contents: "导入结果", addPending: "添加为待确认", partial: "部分联系人添加失败。请检查各行结果并重试失败行。", changed: "确认后目标已更改或预览已过期。请重新获取并核对当前信息。", saved: "已将所选联系人添加为待确认。", incomplete: "信息不足，需要确认" },
  "zh-Hant": { groupTitle: "批次同步群組聯絡人", singleTitle: "新增至本應用程式", help: "將Zoom群組聯絡人匯入本應用程式。不覆寫現有人員資訊，新增聯絡人將處於待確認狀態。同步不會發起通話，也不代表已取得通知同意。", studentHelp: "匯入學生後，請補充學號並確認本人身分、電話號碼及通知同意。", contents: "匯入結果", addPending: "新增為待確認", partial: "部分聯絡人新增失敗。請檢查各列結果並重試失敗列。", changed: "確認後目標已變更或預覽已過期。請重新取得並核對目前資訊。", saved: "已將所選聯絡人新增為待確認。", incomplete: "資訊不足，需要確認" },
  ko: { groupTitle: "그룹 연락처 일괄 동기화", singleTitle: "이 앱에 추가", help: "Zoom 그룹 연락처를 이 앱으로 가져옵니다. 기존 인물 정보를 덮어쓰지 않으며 새 연락처는 확인 대기 상태로 추가됩니다. 동기화는 발신이나 알림 동의를 대신하지 않습니다.", studentHelp: "학생을 가져온 후 학번을 보완하고 본인, 전화번호 및 알림 동의를 확인하세요.", contents: "가져오기 결과", addPending: "확인 대기로 추가", partial: "일부 연락처를 추가하지 못했습니다. 각 행의 결과를 확인하고 실패한 행을 다시 시도하세요.", changed: "확인 후 대상이 변경되었거나 미리보기가 만료되었습니다. 다시 가져와 현재 정보를 확인하세요.", saved: "선택한 연락처를 확인 대기로 추가했습니다.", incomplete: "정보 부족, 확인 필요" },
};
