import type { Locale } from './dictionaries';
export type CampaignSyncDictionary = { search: string; loading: string; adding: string; loadFailed: string; incomplete: string; title: string; destination: string; help: string; empty: string; noCandidates: string; noMatches: string; add: string; permission: string; agentlessRequired: string; unknownType: string; saved: string; resultUnknown: string; type: string };
export const campaignSyncDictionaries: Record<Locale, CampaignSyncDictionary> = {
  ja: { search: "キャンペーン名・IDで検索", loading: "キャンペーンを取得しています…", adding: "追加しています…", loadFailed: "キャンペーンを取得できませんでした。追加済みの定型案内は変更されていません。", incomplete: '一部の候補を取得できませんでした。取得済みの候補と選択を保持しています。「再取得」で続きを確認してください。', title: 'キャンペーンを同期', destination: '追加先: {tenant}', help: 'Zoomのキャンペーンを選択して、この業種の定型案内に追加します。この操作で電話を発信したり、Zoomの設定を変更したりすることはありません。', empty: '定型案内はまだありません。', noCandidates: '追加できるキャンペーン候補がありません。', noMatches: '検索条件に一致する候補がありません。', add: '選択した{count}件を追加', permission: 'キャンペーンの同期には全権アクセスが必要です。管理者に依頼してください。', agentlessRequired: 'Agentless Dialer以外は追加できません。', unknownType: 'キャンペーンの種類を確認できないため追加できません。', saved: '選択したキャンペーンを追加し、最新の一覧を確認しました。', resultUnknown: '保存結果を確認できませんでした。選択を保持しています。再試行すると同じ操作の結果を確認します。', type: '種類' },
  en: { search: "Search by campaign name or ID", loading: "Loading campaigns…", adding: "Adding…", loadFailed: "Campaigns could not be loaded. Previously added campaigns have not changed.", incomplete: 'Some candidates could not be retrieved. Loaded candidates and selections are retained. Refresh to continue.', title: 'Sync campaigns', destination: 'Add to: {tenant}', help: 'Select Zoom campaigns to add to regular outreach for this industry. This does not place calls or change Zoom settings.', empty: 'No regular campaigns have been added.', noCandidates: 'No campaign candidates are available.', noMatches: 'No candidates match your search.', add: 'Add {count} selected', permission: 'Full access is required to sync campaigns. Contact an administrator.', agentlessRequired: 'Only Agentless Dialer campaigns can be added.', unknownType: 'This campaign cannot be added because its type could not be verified.', saved: 'Selected campaigns were added and the latest list was verified.', resultUnknown: 'The save result could not be verified. Your selection is retained. Retry to check the same operation.', type: 'Type' },
  'zh-Hans': { search: "按营销活动名称或ID搜索", loading: "正在获取营销活动…", adding: "正在添加…", loadFailed: "无法获取营销活动。已添加的定期通知未发生变化。", incomplete: '部分候选项获取失败。已保留获取的候选项和选择。请刷新以继续。', title: '同步营销活动', destination: '添加到：{tenant}', help: '选择Zoom营销活动并添加到此行业的定期通知。此操作不会拨打电话或更改Zoom设置。', empty: '尚未添加定期通知。', noCandidates: '没有可用的营销活动候选项。', noMatches: '没有符合搜索条件的候选项。', add: '添加所选{count}项', permission: '同步营销活动需要完整访问权限。请联系管理员。', agentlessRequired: '仅可添加Agentless Dialer营销活动。', unknownType: '无法确认营销活动类型，因此无法添加。', saved: '已添加所选营销活动并确认最新列表。', resultUnknown: '无法确认保存结果。已保留选择。重试将确认同一操作的结果。', type: '类型' },
  'zh-Hant': { search: "依行銷活動名稱或ID搜尋", loading: "正在取得行銷活動…", adding: "正在新增…", loadFailed: "無法取得行銷活動。已新增的定期通知未發生變更。", incomplete: '部分候選項取得失敗。已保留取得的候選項和選取狀態。請重新取得以繼續。', title: '同步行銷活動', destination: '新增至：{tenant}', help: '選取Zoom行銷活動並新增至此行業的定期通知。此操作不會撥打電話或變更Zoom設定。', empty: '尚未新增定期通知。', noCandidates: '沒有可用的行銷活動候選項。', noMatches: '沒有符合搜尋條件的候選項。', add: '新增所選{count}項', permission: '同步行銷活動需要完整存取權限。請聯絡管理員。', agentlessRequired: '僅可新增Agentless Dialer行銷活動。', unknownType: '無法確認行銷活動類型，因此無法新增。', saved: '已新增所選行銷活動並確認最新清單。', resultUnknown: '無法確認儲存結果。已保留選取項目。重試將確認同一操作的結果。', type: '類型' },
  ko: { search: "캠페인 이름 또는 ID로 검색", loading: "캠페인을 가져오는 중…", adding: "추가하는 중…", loadFailed: "캠페인을 가져오지 못했습니다. 이미 추가된 정기 안내는 변경되지 않았습니다.", incomplete: '일부 후보를 가져오지 못했습니다. 가져온 후보와 선택 항목은 유지됩니다. 새로고침하여 계속하세요.', title: '캠페인 동기화', destination: '추가 대상: {tenant}', help: 'Zoom 캠페인을 선택하여 이 업종의 정기 안내에 추가합니다. 이 작업은 전화를 걸거나 Zoom 설정을 변경하지 않습니다.', empty: '추가된 정기 안내가 없습니다.', noCandidates: '사용 가능한 캠페인 후보가 없습니다.', noMatches: '검색 조건과 일치하는 후보가 없습니다.', add: '선택한 {count}개 추가', permission: '캠페인 동기화에는 전체 접근 권한이 필요합니다. 관리자에게 문의하세요.', agentlessRequired: 'Agentless Dialer 캠페인만 추가할 수 있습니다.', unknownType: '캠페인 유형을 확인할 수 없어 추가할 수 없습니다.', saved: '선택한 캠페인을 추가하고 최신 목록을 확인했습니다.', resultUnknown: '저장 결과를 확인할 수 없습니다. 선택 항목은 유지됩니다. 다시 시도하면 같은 작업의 결과를 확인합니다.', type: '유형' },
};
