import { audioImportCandidates, importAudioMessages, audioImportOperation, getImportedAudioMessage, messageCatalog } from "./message-imports";
import { editImportedAudioMessage, unlinkImportedAudioMessage } from "./message-edit";
import { importedMessageAudio } from "./message-audio";
import { listPurposeCampaigns, purposeCampaignCandidates, purposeCampaignOperation, savePurposeCampaign } from "./purpose-campaign-bindings";
import { startRegularGroupSync } from "./regular-group-sync";
import { bindDefaultGroup, defaultGroupCandidates, listOutreachGroups } from "./default-groups";
import { getDefaultGroupDetail, startRegistrationGroupSync, getRegistrationSyncOperation, advanceRegistrationSync, linkRegistrationMember } from "./registration-group-sync";
import { groupSyncCandidates, syncContactLists, groupSyncOperation } from "./group-sync";
import { updateZaadResident, deleteZaadResident } from "./residents";
import { listResourceBindings, previewResourceBinding, saveResourceBinding } from "./resource-bindings";
import { previewZoomCrmImport, applyZoomCrmImport } from "./zoom-crm-imports";
import { ZaadZoomClient } from "./zoom-client";
import { executeDispatch, getDispatch, inspectDispatchConfirmation, listDispatches, preflightDispatch, prepareDispatch } from "./dispatches";
import type { Hono } from "hono";
import type { ZaadApiEnvironment } from "./api-routes";
import { withOutreach, outreachJson, requireSameOrigin, boundedBody } from "./outreach-api";
import { deleteContact, createContact, getContact, listContacts, updateContact } from "./contacts";
import { applyCrmImport, getCrmImport, previewCrmImport } from "./crm-imports";
import { getRegularCampaign, pauseRegularCampaign, bindCampaigns, campaignSyncCandidates, campaignSyncOperation, listRegularCampaigns } from "./campaign-bindings";
import { deleteZoomGroup, deleteZoomMember, linkZoomMember, saveZoomGroup, saveZoomMember, zoomGroupMembers } from "./zoom-groups";
import { getOutreachMessage, listOutreachMessages, requireMessageAudio, retireOutreachMessage, saveOutreachMessage } from "./message-revisions";
import { getZaadConnection } from "./resources";
import { audioCapabilities } from "@/lib/zaad/message-contracts";
import { choice, OutreachContractError, PERSON_ORIGINS, record, fields, whole } from "@/lib/zaad/outreach-contracts";
import { CRM_CSV_MAX_BYTES } from "@/lib/zaad/crm-csv-schema";
import { registerMunicipalRoutes } from "./municipal/api-routes";
export function registerOutreachRoutes(app: Hono<ZaadApiEnvironment>) {
  registerMunicipalRoutes(app);
  const root = "/admin/zaad";
  app.get(`${root}/purpose-campaigns`, c => withOutreach(c, "VIEW", (db, scope) => listPurposeCampaigns(db, scope)));
  app.get(`${root}/purpose-campaigns/operations/:operationKey`, c => withOutreach(c, "UPDATE", (db, scope) => purposeCampaignOperation(db, scope, c.req.param("operationKey"))));
  app.get(`${root}/purpose-campaigns/:mode/:purpose/candidates`, c => withOutreach(c, "UPDATE", (db, scope) => purposeCampaignCandidates(db, scope, c.req.param("mode"), c.req.param("purpose"), c.req.query("cursor"))));
  app.put(`${root}/purpose-campaigns/:mode/:purpose`, c => withOutreach(c, "UPDATE", async (db, scope) => savePurposeCampaign(db, scope, c.req.param("mode"), c.req.param("purpose"), await outreachJson(c))));
  app.get(`${root}/resource-bindings`, c => withOutreach(c, "VIEW", (db, scope) => listResourceBindings(db, scope)));
  app.post(`${root}/resource-bindings/preview`, c => withOutreach(c, "UPDATE", async (db, scope) => previewResourceBinding(db, scope, await outreachJson(c))));
  app.put(`${root}/resource-bindings`, c => withOutreach(c, "UPDATE", async (db, scope) => saveResourceBinding(db, scope, await outreachJson(c))));
  app.get(`${root}/one-time-dispatches`, c => withOutreach(c, "VIEW", (db, scope) => listDispatches(db, scope)));
  app.get(`${root}/one-time-dispatches/:id`, c => withOutreach(c, "VIEW", (db, scope) => c.req.query("confirmation") === "true" ? inspectDispatchConfirmation(db, scope, c.req.param("id")) : getDispatch(db, scope, c.req.param("id"))));
  app.post(`${root}/one-time-dispatches/preflight`, c => withOutreach(c, "CREATE", async (db, scope) => preflightDispatch(db, scope, await outreachJson(c))));
  app.post(`${root}/one-time-dispatches`, c => withOutreach(c, "CREATE", async (db, scope) => prepareDispatch(db, scope, await outreachJson(c))));
  app.post(`${root}/one-time-dispatches/:id/execute`, c => withOutreach(c, "UPDATE", async (db, scope) => executeDispatch(db, scope, c.req.param("id"), await outreachJson(c))));
  app.post(`${root}/one-time-dispatches/:id/rerun`, c => withOutreach(c, "CREATE", async (db, scope) => {
    const body = record(await outreachJson(c));
    if (body.parentDispatchId !== c.req.param("id")) throw new OutreachContractError("INVALID_PARENT_DISPATCH");
    return preflightDispatch(db, scope, body);
  }));
  app.get(`${root}/flows`, c => withOutreach(c, "VIEW", async (db, scope) => {
    const client = await ZaadZoomClient.fromDatabase(db, scope.siteKey);
    const bindings = await db.zoomResourceBinding.findMany({ where: { ownerSiteKey: scope.siteKey, accountId: client.accountId, resourceType: "FLOW", tombstone: false } });
    const items = [];
    for (const binding of bindings) { const flow = await client.getFlow(binding.zoomId); items.push({ id: binding.id, name: flow.name, zoomId: flow.id, version: binding.version, executionReady: false }); }
    return { tenantKey: scope.siteKey, items, total: items.length, nextCursor: null };
  }));
  app.get(`${root}/connection`, c => withOutreach(c, "VIEW", async (db, scope) => ({ tenantKey: scope.siteKey, connection: await getZaadConnection(db, scope.siteKey), fullAccess: scope.all, liveExecution: scope.live, capabilities: { audio: audioCapabilities }, observedAt: new Date().toISOString() })));
  app.get(`${root}/contacts`, c => withOutreach(c, "VIEW", (db, scope) => listContacts(db, scope, { search: c.req.query("query"), cursor: c.req.query("cursor"), ...(c.req.query("limit") ? { limit: Number(c.req.query("limit")) } : {}) })));
  app.post(`${root}/contacts`, c => withOutreach(c, "CREATE", async (db, scope) => ({ tenantKey: scope.siteKey, contact: await createContact(db, scope, await outreachJson(c)) })));
  app.post(`${root}/contacts/imports/preview`, c => withOutreach(c, "CREATE", async (db, scope) => {
    requireSameOrigin(c.req.raw);
    if (c.req.header("content-type")?.split(";")[0] !== "text/csv") throw new OutreachContractError("INVALID_CONTENT_TYPE");
    return previewCrmImport(db, scope, { bytes: new TextEncoder().encode(await boundedBody(c.req.raw, CRM_CSV_MAX_BYTES)), operationKey: c.req.header("x-operation-key") ?? "" });
  }));
  app.post(`${root}/contacts/imports`, c => withOutreach(c, "CREATE", async (db, scope) => applyCrmImport(db, scope, await outreachJson(c))));
  app.get(`${root}/contacts/imports/:jobId`, c => withOutreach(c, "VIEW", (db, scope) => getCrmImport(db, scope, c.req.param("jobId"))));
  app.patch(`${root}/contacts/:id/legacy`, c => withOutreach(c, "UPDATE", async (db, scope) => {
    await getContact(db, scope, "DISASTER_RADIO", c.req.param("id"));
    await updateZaadResident(db, scope.siteKey, scope.actorId, c.req.param("id"), await outreachJson(c));
    return { tenantKey: scope.siteKey, contact: await getContact(db, scope, "DISASTER_RADIO", c.req.param("id")) };
  }));
  app.delete(`${root}/contacts/:id/legacy`, c => withOutreach(c, "DELETE", async (db, scope) => {
    await getContact(db, scope, "DISASTER_RADIO", c.req.param("id"));
    const body = record(await outreachJson(c)); fields(body, ["revision"]);
    return { tenantKey: scope.siteKey, ...await deleteZaadResident(db, scope.siteKey, scope.actorId, c.req.param("id"), whole(body.revision)) };
  }));
  app.get(`${root}/contacts/:id`, c => withOutreach(c, "VIEW", async (db, scope) => ({ tenantKey: scope.siteKey, contact: await getContact(db, scope, choice(c.req.query("origin"), PERSON_ORIGINS), c.req.param("id")) })));
  app.delete(`${root}/contacts/:id`, c => withOutreach(c, "DELETE", async (db, scope) => deleteContact(db, scope, choice(c.req.query("origin"), PERSON_ORIGINS), c.req.param("id"), await outreachJson(c))));
  app.patch(`${root}/contacts/:id`, c => withOutreach(c, "UPDATE", async (db, scope) => ({ tenantKey: scope.siteKey, contact: await updateContact(db, scope, choice(c.req.query("origin"), PERSON_ORIGINS), c.req.param("id"), await outreachJson(c)) })));
  app.post(`${root}/contact-lists/:id/crm-sync/preview`, c => withOutreach(c, "CREATE", async (db, scope) => previewZoomCrmImport(db, scope, c.req.param("id"), await outreachJson(c))));
  app.post(`${root}/contact-lists/:id/crm-sync`, c => withOutreach(c, "CREATE", async (db, scope) => applyZoomCrmImport(db, scope, c.req.param("id"), await outreachJson(c))));
  app.get(`${root}/contact-lists/:id/crm-sync/:jobId`, c => withOutreach(c, "VIEW", (db, scope) => getCrmImport(db, scope, c.req.param("jobId"))));
  app.post(`${root}/contact-lists/:id/contacts/:contactId/import`, c => withOutreach(c, "CREATE", async (db, scope) => {
    const body = record(await outreachJson(c));
    return previewZoomCrmImport(db, scope, c.req.param("id"), { ...body, contactIds: [c.req.param("contactId")] });
  }));
  app.get(`${root}/default-groups/:id/candidates`, c => {
    c.header("Cache-Control", "no-store");
    return withOutreach(c, "UPDATE", (db, scope) => defaultGroupCandidates(db, scope, c.req.param("id"), c.req.query("cursor")));
  });
  app.get(`${root}/default-groups/:id`, c => withOutreach(c, "VIEW", (db, scope) => getDefaultGroupDetail(db, scope, c.req.param("id"), { cursor: c.req.query("cursor"), query: c.req.query("query") })));
  app.put(`${root}/default-groups/:id`, c => withOutreach(c, "UPDATE", async (db, scope) => bindDefaultGroup(db, scope, c.req.param("id"), await outreachJson(c))));
  app.post(`${root}/default-groups/:id/sync`, c => withOutreach(c, "UPDATE", async (db, scope) => startRegistrationGroupSync(db, scope, c.req.param("id"), await outreachJson(c)), 202));
  app.get(`${root}/sync-operations/:operationId`, c => withOutreach(c, "UPDATE", (db, scope) => getRegistrationSyncOperation(db, scope, c.req.param("operationId"))));
  app.post(`${root}/sync-operations/:operationId/advance`, c => withOutreach(c, "UPDATE", async (db, scope) => { await outreachJson(c); return advanceRegistrationSync(db, scope, c.req.param("operationId")); }));
  app.post(`${root}/default-groups/:id/members/:memberId/link`, c => withOutreach(c, "UPDATE", async (db, scope) => linkRegistrationMember(db, scope, c.req.param("id"), c.req.param("memberId"), await outreachJson(c))));
  app.get(`${root}/contact-lists/sync-candidates`, c => withOutreach(c, "UPDATE", (db, scope) => groupSyncCandidates(db, scope, undefined, c.req.query("cursor"))));
  app.post(`${root}/contact-lists/sync-bindings`, c => withOutreach(c, "UPDATE", async (db, scope) => syncContactLists(db, scope, await outreachJson(c))));
  app.get(`${root}/contact-lists/sync-operations/:operationKey`, c => withOutreach(c, "UPDATE", (db, scope) => groupSyncOperation(db, scope, c.req.param("operationKey"))));
  app.get(`${root}/contact-lists`, c => withOutreach(c, "VIEW", (db, scope) => listOutreachGroups(db, scope)));
  app.post(`${root}/contact-lists`, c => withOutreach(c, "CREATE", async (db, scope) => saveZoomGroup(db, scope, await outreachJson(c))));
  app.post(`${root}/contact-lists/:id/sync`, c => withOutreach(c, "UPDATE", async (db, scope) => startRegularGroupSync(db, scope, c.req.param("id"), await outreachJson(c)), 202));
  app.get(`${root}/contact-lists/:id`, c => withOutreach(c, "VIEW", (db, scope) => zoomGroupMembers(db, scope, c.req.param("id"), undefined, true)));
  app.patch(`${root}/contact-lists/:id`, c => withOutreach(c, "UPDATE", async (db, scope) => saveZoomGroup(db, scope, await outreachJson(c), c.req.param("id"))));
  app.delete(`${root}/contact-lists/:id`, c => withOutreach(c, "DELETE", async (db, scope) => deleteZoomGroup(db, scope, c.req.param("id"), await outreachJson(c))));
  app.get(`${root}/contact-lists/:id/contacts`, c => withOutreach(c, "VIEW", (db, scope) => zoomGroupMembers(db, scope, c.req.param("id"))));
  app.post(`${root}/contact-lists/:id/contacts`, c => withOutreach(c, "CREATE", async (db, scope) => saveZoomMember(db, scope, c.req.param("id"), await outreachJson(c))));
  app.patch(`${root}/contact-lists/:id/contacts/:contactId`, c => withOutreach(c, "UPDATE", async (db, scope) => saveZoomMember(db, scope, c.req.param("id"), await outreachJson(c), c.req.param("contactId"))));
  app.delete(`${root}/contact-lists/:id/contacts/:contactId`, c => withOutreach(c, "DELETE", async (db, scope) => deleteZoomMember(db, scope, c.req.param("id"), c.req.param("contactId"), await outreachJson(c))));
  app.post(`${root}/contact-lists/:id/contacts/:contactId/link`, c => withOutreach(c, "UPDATE", async (db, scope) => linkZoomMember(db, scope, c.req.param("id"), c.req.param("contactId"), await outreachJson(c))));
  app.get(`${root}/campaigns/sync-candidates`, c => withOutreach(c, "VIEW", (db, scope) => campaignSyncCandidates(db, scope, undefined, c.req.query("cursor"))));
  app.post(`${root}/campaigns/sync-bindings`, c => withOutreach(c, "UPDATE", async (db, scope) => bindCampaigns(db, scope, await outreachJson(c))));
  app.get(`${root}/campaigns/sync-operations/:operationKey`, c => withOutreach(c, "VIEW", (db, scope) => campaignSyncOperation(db, scope, c.req.param("operationKey"))));
  app.get(`${root}/campaigns`, c => withOutreach(c, "VIEW", (db, scope) => listRegularCampaigns(db, scope)));
  app.get(`${root}/campaigns/:id`, c => withOutreach(c, "VIEW", (db, scope) => getRegularCampaign(db, scope, c.req.param("id"))));
  app.patch(`${root}/campaigns/:id/status`, c => withOutreach(c, "UPDATE", async (db, scope) => pauseRegularCampaign(db, scope, c.req.param("id"), await outreachJson(c))));
  app.get(`${root}/message-catalog`, c => withOutreach(c, "VIEW", (db, scope) => messageCatalog(db, scope)));
  app.get(`${root}/message-import/candidates`, c => withOutreach(c, ["CREATE", "UPDATE"], (db, scope) => audioImportCandidates(db, scope)));
  app.post(`${root}/message-import`, c => withOutreach(c, ["CREATE", "UPDATE"], async (db, scope) => importAudioMessages(db, scope, await outreachJson(c))));
  app.get(`${root}/message-import/operations/:key`, c => withOutreach(c, ["CREATE", "UPDATE"], (db, scope) => audioImportOperation(db, scope, c.req.param("key"))));
  app.get(`${root}/imported-audio-messages/:id`, c => withOutreach(c, "VIEW", (db, scope) => getImportedAudioMessage(db, scope, c.req.param("id"))));
  app.get(`${root}/imported-audio-messages/:id/audio`, c => withOutreach(c, "VIEW", (db, scope) => importedMessageAudio(db, scope, c.req.param("id"), c.req.raw)));
  app.patch(`${root}/imported-audio-messages/:id`, c => withOutreach(c, ["VIEW", "UPDATE"], async (db, scope) => editImportedAudioMessage(db, scope, c.req.param("id"), await outreachJson(c))));
  app.delete(`${root}/imported-audio-messages/:id`, c => withOutreach(c, ["VIEW", "DELETE"], async (db, scope) => unlinkImportedAudioMessage(db, scope, c.req.param("id"), await outreachJson(c))));
  app.get(`${root}/messages`, c => withOutreach(c, "VIEW", (db, scope) => listOutreachMessages(db, scope)));
  app.post(`${root}/messages`, c => withOutreach(c, "CREATE", async (db, scope) => saveOutreachMessage(db, scope, await outreachJson(c))));
  app.get(`${root}/messages/:id`, c => withOutreach(c, "VIEW", (db, scope) => getOutreachMessage(db, scope, c.req.param("id"))));
  app.patch(`${root}/messages/:id`, c => withOutreach(c, "UPDATE", async (db, scope) => saveOutreachMessage(db, scope, await outreachJson(c), c.req.param("id"))));
  app.delete(`${root}/messages/:id`, c => withOutreach(c, "DELETE", async (db, scope) => retireOutreachMessage(db, scope, c.req.param("id"), await outreachJson(c), true)));
  app.post(`${root}/messages/:id/retire`, c => withOutreach(c, "UPDATE", async (db, scope) => retireOutreachMessage(db, scope, c.req.param("id"), await outreachJson(c))));
  app.post(`${root}/messages/:id/sync`, c => withOutreach(c, "UPDATE", async (db, scope) => requireMessageAudio(db, scope, c.req.param("id"), record(await outreachJson(c)).snapshotId)));
  app.get(`${root}/messages/:id/snapshots/:snapshotId/preview`, c => withOutreach(c, "VIEW", (db, scope) => requireMessageAudio(db, scope, c.req.param("id"), c.req.param("snapshotId"))));
}
