"use client";

import Link from "next/link";
import { useI18n } from "@/app/i18n/LanguageProvider";
import { ConsultationAvailability } from "./ConsultationAvailability";
import { univContent, type UniversityContent, type UniversitySectionKey } from "./content";

type Page = "home" | UniversitySectionKey | "faq" | "news" | "consultation";
const paths: Record<UniversitySectionKey, string> = { admissions: "/admissions", academics: "/academics", "campus-life": "/campus-life", scholarships: "/scholarships", careers: "/careers" };
function Glyph({ children }: { children: string }) { return <span aria-hidden="true" className="inline-grid h-11 w-11 place-items-center rounded-xl bg-cyan-50 text-xl font-bold text-blue-800">{children}</span>; }

export function UniversityPortal({ page }: { page: Page }) {
  const { locale } = useI18n(); const c = univContent[locale];
  return <div className="flex min-h-screen flex-col bg-white text-slate-900"><header className="bg-slate-950 text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><Link href="/" className="font-semibold">{c.siteName}<span className="ml-2 text-xs font-normal text-cyan-300">{c.siteNameRoman}</span></Link><Link href="/consultation" className="rounded-full bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950">{c.nav.consultation}</Link></div><nav className="mx-auto flex max-w-7xl gap-5 overflow-x-auto px-5 pb-4 text-sm text-slate-200">{Object.entries(c.nav).map(([key, label]) => <Link className="whitespace-nowrap hover:text-cyan-300" href={key in paths ? paths[key as UniversitySectionKey] : `/${key}`} key={key}>{label}</Link>)}</nav></header><main className="mx-auto w-full max-w-7xl flex-1 px-5 py-12">{page === "home" ? <Home c={c}/> : page === "consultation" ? <Consultation c={c}/> : page === "faq" ? <Faq c={c}/> : page === "news" ? <News c={c}/> : <Section c={c} section={page}/>}</main><footer className="mt-auto bg-slate-950 px-5 py-8 text-sm text-slate-300"><div className="mx-auto max-w-7xl">{c.siteName} · {c.portalLabel}</div></footer></div>;
}
function Home({ c }: { c: UniversityContent }) { return <><section className="rounded-3xl bg-gradient-to-br from-slate-950 via-blue-950 to-cyan-900 p-8 text-white md:p-14"><p className="text-sm font-semibold tracking-[.2em] text-cyan-300">{c.portalLabel}</p><h1 className="mt-5 whitespace-pre-line text-4xl font-bold leading-tight md:text-6xl">{c.home.title}</h1><p className="mt-6 max-w-2xl text-lg text-slate-200">{c.home.lead}</p><Link href="/consultation" className="mt-9 inline-block rounded-full bg-cyan-400 px-6 py-3 font-semibold text-slate-950">{c.home.chooseConsultation} →</Link></section><section className="mt-14"><h2 className="text-2xl font-bold">{c.home.supportHeading}</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{(Object.keys(c.sections) as UniversitySectionKey[]).map((key, index) => <Link href={paths[key]} key={key} className="rounded-2xl border border-slate-200 p-6 transition hover:-translate-y-1 hover:border-cyan-500 hover:shadow-lg"><Glyph>{["◫","⌁","◈","◇","↗"][index]}</Glyph><h3 className="mt-5 text-lg font-bold">{c.sections[key].title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{c.sections[key].lead}</p></Link>)}</div></section></>; }
function Section({ c, section }: { c: UniversityContent; section: UniversitySectionKey }) { const item=c.sections[section]; return <><p className="text-sm font-semibold text-cyan-700">{c.portalLabel}</p><h1 className="mt-3 text-4xl font-bold">{item.title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">{item.lead}</p><div className="mt-10 grid gap-4 md:grid-cols-3">{item.items.map(([title, description]) => <article key={title} className="rounded-2xl border border-slate-200 p-6"><h2 className="font-bold">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{description}</p></article>)}</div></>; }
function Consultation({ c }: { c: UniversityContent }) { const labels={ admissions: c.consultation.services[0][0], "student-support": c.consultation.services[1][0], careers: c.consultation.services[2][0] }; return <><h1 className="text-4xl font-bold">{c.consultation.title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">{c.consultation.lead}</p><section className="mt-10 grid border border-slate-200 md:grid-cols-2"><article className="flex min-h-80 flex-col p-7 md:border-r md:border-slate-200"><Glyph>▢</Glyph><h2 className="mt-5 text-2xl font-bold">{c.consultation.reserveTitle}</h2><p className="mt-3 leading-7 text-slate-600">{c.consultation.reserveLead}</p><button className="mt-auto rounded-lg bg-blue-800 px-5 py-4 font-semibold text-white">{c.consultation.reserveAction} →</button></article><article className="flex min-h-80 flex-col p-7"><Glyph>◉</Glyph><h2 className="mt-5 text-2xl font-bold">{c.consultation.instantTitle}</h2><p className="mt-3 leading-7 text-slate-600">{c.consultation.instantLead}</p><p className="mt-3 text-sm text-slate-600">{c.consultation.instantExtra}</p><p className="mt-4 text-sm font-semibold text-blue-900">{c.consultation.hours}</p><button disabled className="mt-auto rounded-lg border border-slate-300 px-5 py-4 font-semibold text-slate-500">{c.consultation.instantAction} →</button></article></section><ConsultationAvailability labels={labels}/><section className="mt-12 bg-blue-50 p-7"><h2 className="text-2xl font-bold">{c.consultation.beforeTitle}</h2><div className="mt-6 grid border-l border-t border-blue-200 md:grid-cols-3">{c.consultation.before.map(([title, description], index)=><article className="border-b border-r border-blue-200 bg-white p-5" key={title}><Glyph>{["▣","✓","▢"][index]}</Glyph><h3 className="mt-4 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p></article>)}</div></section><section className="mt-12"><h2 className="text-2xl font-bold">{c.consultation.faqTitle}</h2><div className="mt-5 w-full border border-slate-200">{c.faq.questions.slice(0,3).map(([question,answer])=><details className="border-b border-slate-200 last:border-0" key={question}><summary className="cursor-pointer px-5 py-5 font-semibold">{question}</summary><p className="px-5 pb-5 text-slate-600">{answer}</p></details>)}</div></section><aside className="mt-10 border-l-4 border-blue-500 bg-blue-50 p-5"><h2 className="font-bold">{c.consultation.privacyTitle}</h2><p className="mt-2 text-sm text-slate-600">{c.consultation.privacyLead}</p></aside></>; }
function Faq({ c }: { c: UniversityContent }) { return <><h1 className="text-4xl font-bold">{c.faq.title}</h1><p className="mt-4 text-slate-600">{c.faq.lead}</p><div className="mt-8 w-full border border-slate-200">{c.faq.questions.map(([question,answer])=><details className="border-b border-slate-200 last:border-0" key={question}><summary className="cursor-pointer px-5 py-5 font-semibold">{question}</summary><p className="px-5 pb-5 text-slate-600">{answer}</p></details>)}</div></>; }
function News({ c }: { c: UniversityContent }) { return <><h1 className="text-4xl font-bold">{c.news.title}</h1><p className="mt-4 text-slate-600">{c.news.lead}</p><div className="mt-8 divide-y border-y border-slate-200">{c.news.articles.map(([date,title,category])=><article className="py-6" key={title}><p className="text-sm text-slate-500">{date} · {category}</p><h2 className="mt-2 text-xl font-bold">{title}</h2></article>)}</div></>; }
