"use client";
import { Feedback } from "@/app/components/admin/Feedback";
import { useEffect, useState, type ReactNode } from "react";
import { useI18n } from "@/app/i18n/LanguageProvider";
import { Select } from "@/app/components/Select";
import { Checkbox } from "@/app/components/Checkbox";
import type { MunicipalPurpose, Availability } from "@/lib/zaad/municipal/contracts";
import type { ContactDto } from "@/lib/zaad/outreach-contracts";
import { outreachRequest } from "./outreach-client";
import { registrationInputClass as input, outreachPrimary as primary, outreachSecondary as secondary } from "@/app/notifications/register/StudentNotificationRegistration";
export function MunicipalTargetForm({ contact, purpose, busy, save, cancel, initial, onDirty }: { initial?: { businessEvidence: unknown; excluded: boolean }; onDirty?: () => void; contact: ContactDto; purpose: MunicipalPurpose; busy: boolean; save: (evidence: unknown, excluded: boolean) => void; cancel: () => void }) {
  const { t } = useI18n(), w = t.municipalWorkflows, m = t.municipalOutreach, z = t.admin.zaad;
  const [availability, setAvailability] = useState<{ revision: number; confirmed: Availability | null } | null>(null), [error, setError] = useState("");
  const [availabilityContactId, setAvailabilityContactId] = useState<string | null>(null), [availabilityError, setAvailabilityError] = useState(false), [reload, setReload] = useState(0);
  const availabilityLoading = purpose === "ELDER_WATCH" && availabilityContactId !== contact.reference.id;
  useEffect(() => { if (purpose !== "ELDER_WATCH") return; const controller = new AbortController(); outreachRequest<{ contact: { availability: typeof availability } }>("lg", `contacts/${encodeURIComponent(contact.reference.id)}?origin=MUNICIPAL_CONTACT`, { signal: controller.signal }).then(result => { if (!controller.signal.aborted) { setAvailability(result.contact.availability); setAvailabilityContactId(contact.reference.id); setAvailabilityError(false); } }).catch(() => { if (!controller.signal.aborted) { setAvailabilityContactId(contact.reference.id); setAvailabilityError(true); } }); return () => controller.abort(); }, [contact.reference.id, purpose, reload]);
  const saved = initial?.businessEvidence && typeof initial.businessEvidence === "object" ? initial.businessEvidence as Record<string, unknown> : {};
  const initialDate = (value: unknown) => typeof value === "string" && Number.isFinite(Date.parse(value)) ? new Date(Date.parse(value) + 9 * 3600000).toISOString().slice(0, 16) : "";
  const field = (name: string, label: string, type = "text", required = true, defaultValue?: string) => <label className="block">{label}<input name={name} className={input} type={type} required={required} maxLength={type === "text" ? 500 : undefined} defaultValue={defaultValue ?? (type === "datetime-local" ? initialDate(saved[name]) : String(saved[name] ?? ""))} /></label>;
  const select = (name: string, label: string, options: [string, string][]) => <label className="block">{label}<Select name={name} required defaultValue={String(saved[name] ?? "")}><option value="">{m.choose}</option>{options.map(([key, text]) => <option value={key} key={key}>{text}</option>)}</Select></label>;
  let fields: ReactNode;
  if (purpose === "ELDER_WATCH") fields = availabilityLoading ? <p role="status">{z.common.loading}</p> : availabilityError ? <Feedback tone="error" action={<button type="button" className={secondary} onClick={() => { setAvailabilityContactId(null); setAvailabilityError(false); setReload(value => value + 1); }}>{z.common.retry}</button>}>{z.common.failure}</Feedback> : <div className="space-y-3"><p>{w.availableRevision}: {availability?.confirmed ? availability.revision : w.unconfirmed}</p><p className="text-sm text-fg-muted">{m.availability}</p></div>;
  else if (purpose === "PROCEDURE_SUPPORT") fields = <>{field("procedureRef", w.recordReference)}{field("noticeSentAt", w.noticeSent, "datetime-local")}{field("reminderAt", w.reminderAt, "datetime-local")}{select("status", w.procedureStatus, [["INCOMPLETE", w.incomplete], ["VERIFIED_COMPLETE", w.complete], ["UNKNOWN", w.unknown]])}{field("statusVerifiedAt", w.verifiedAt, "datetime-local")}<label className="flex gap-3"><Checkbox name="individualCallRequired" defaultChecked={saved.individualCallRequired === true} />{w.individualRequired}</label>{field("reason", w.reason)}{field("deadline", w.deadline, "datetime-local")}</>;
  else if (purpose === "SERVICE_CONFIRMATION") fields = <>{field("serviceRef", w.recordReference)}{select("serviceKind", w.serviceKind, [["VISIT", w.visit], ["TRANSPORT", w.transport], ["MEAL", w.meal]])}{field("scheduleId", w.scheduleId)}{field("scheduleVersion", w.scheduleVersion, "number")}{field("startsAt", w.startsAt, "datetime-local")}{select("status", w.scheduleStatus, [["CONFIRMED", w.scheduleConfirmed], ["CHANGED", w.scheduleChanged], ["CANCELLED", w.scheduleCancelled], ["UNKNOWN", w.unknown]])}<label className="flex gap-3"><Checkbox name="registeredUserVerified" defaultChecked={saved.registeredUserVerified === true} />{w.registeredUser}</label><MunicipalTimeFields prefix="contact" value={saved.contactWindow as Availability | undefined} /></>;
  else fields = <>{field("incidentRef", w.incidentRef)}{field("verifiedAt", w.verifiedAt, "datetime-local")}<fieldset className="space-y-2"><legend>{m.district}</legend>{Object.entries(m.districts).map(([key, label]) => <label key={key} className="flex gap-3"><Checkbox name="districts" value={key} defaultChecked={Array.isArray(saved.districts) && saved.districts.includes(key)} />{label}</label>)}</fieldset>{field("guidance", w.guidance)}{field("officeUrl", w.officialOffice, "url")}{field("callerPhone", w.callerPhone, "tel")}{field("publicationVerifiedAt", w.publishedAt, "datetime-local")}</>;
  return <form className="space-y-4" onChange={onDirty} onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget), str = (key: string) => String(form.get(key) ?? ""), date = (key: string) => new Date(`${str(key)}:00+09:00`).toISOString(); try {
    let evidence: unknown;
    if (purpose === "ELDER_WATCH") { if (availabilityLoading || availabilityError || !availability?.confirmed) throw new Error("AVAILABILITY_NOT_CONFIRMED"); evidence = { purpose, availabilityRevision: availability.revision, confirmedAvailability: availability.confirmed }; }
    else if (purpose === "PROCEDURE_SUPPORT") evidence = { purpose, procedureRef: str("procedureRef"), noticeSentAt: date("noticeSentAt"), reminderAt: date("reminderAt"), status: str("status"), statusVerifiedAt: date("statusVerifiedAt"), individualCallRequired: form.has("individualCallRequired"), reason: str("reason"), deadline: date("deadline") };
    else if (purpose === "SERVICE_CONFIRMATION") evidence = { purpose, serviceRef: str("serviceRef"), serviceKind: str("serviceKind"), scheduleId: str("scheduleId"), scheduleVersion: Number(str("scheduleVersion")), startsAt: date("startsAt"), status: str("status"), registeredUserVerified: form.has("registeredUserVerified"), contactWindow: municipalTimeValues(form, "contact") };
    else evidence = { purpose, incidentRef: str("incidentRef"), verifiedBy: "server-assigned", verifiedAt: date("verifiedAt"), districts: form.getAll("districts"), guidance: str("guidance"), officeUrl: str("officeUrl"), callerPhone: str("callerPhone"), publicationVerifiedAt: date("publicationVerifiedAt") };
    save(evidence, form.has("excluded"));
  } catch { setError(m.invalid); } }}><h3 className="font-semibold">{contact.name}</h3>{error && <Feedback tone="error">{error}</Feedback>}<fieldset disabled={busy} className="space-y-4">{fields}<label className="flex gap-3"><Checkbox name="excluded" defaultChecked={initial?.excluded} />{w.excluded}</label></fieldset><div className="flex justify-end gap-3"><button type="button" className={secondary} disabled={busy} onClick={cancel}>{z.common.cancel}</button><button className={primary} disabled={busy || (purpose === "ELDER_WATCH" && (availabilityLoading || availabilityError || !availability?.confirmed))}>{w.saveTargets}</button></div></form>;
}
export function MunicipalTimeFields({ prefix, value }: { prefix: string; value?: Availability }) {
  const { t } = useI18n(), m = t.municipalOutreach;
  return <fieldset className="space-y-3"><legend className="mb-2 font-medium">{t.municipalWorkflows.schedule}</legend><div className="flex flex-wrap gap-3">{m.weekdays.map((day, index) => <label key={day} className="flex gap-2"><Checkbox name={`${prefix}Weekdays`} value={index} defaultChecked={value?.weekdays.includes(index)} />{day}</label>)}</div><div className="grid grid-cols-2 gap-3"><label>{m.start}<input className={input} required type="time" name={`${prefix}Start`} defaultValue={value?.windows[0]?.start} /></label><label>{m.end}<input className={input} required type="time" name={`${prefix}End`} defaultValue={value?.windows[0]?.end} /></label></div></fieldset>;
}
export function municipalTimeValues(form: FormData, prefix: string): Availability { return { weekdays: form.getAll(`${prefix}Weekdays`).map(Number), windows: [{ start: String(form.get(`${prefix}Start`)), end: String(form.get(`${prefix}End`)) }] }; }
