"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useI18n } from "@/app/i18n/LanguageProvider";
import { Checkbox } from "@/app/components/Checkbox";
import { Select } from "@/app/components/Select";
import { ModalDialog } from "@/app/components/admin/ModalDialog";
import { MUNICIPAL_PURPOSES, purposePath, purposeTopic, QUESTION_VERSION, type MunicipalPurpose, type Availability, type Answer } from "@/lib/zaad/municipal/contracts";
import { OUTREACH_VOICES } from "@/lib/zaad/message-contracts";
import type { ContactDto } from "@/lib/zaad/outreach-contracts";
import { outreachAll, outreachMutation, outreachRequest, type ListResult } from "./outreach-client";
import { OutreachFailure, OutreachLoading, type OutreachPanelProps } from "./OutreachView";
import { MunicipalTargetForm, MunicipalTimeFields, municipalTimeValues } from "./MunicipalTargetForm";
import { MunicipalCases } from "./MunicipalCases";
import { registrationInputClass as input, outreachPrimary as primary, outreachSecondary as secondary } from "@/app/notifications/register/StudentNotificationRegistration";
type Workflow = { id: string; workflowId: string; revision: number; purpose: MunicipalPurpose; name: string; settings: { body: string; voiceId: string; schedule: Availability; maxRetries: number; retryIntervalMinutes: number; flowBindingId: string | null }; assigneeId: string; dueAt: string };
type RunResult = { targets: RunTarget[]; eventIssues: { id: string; errorCode: string | null; receivedAt: string }[] };
type DraftTarget = { contactId: string; businessEvidence: unknown; excluded: boolean };
type Target = { id: string; version: number; contactId: string; name: string; eligible: boolean; reasons: string[]; excluded: boolean; businessEvidence: unknown };
type Assignee = { id: string; name: string };
type Preview = { snapshotId: string; digest: string; eligible: number; excluded: Target[]; readiness: { ready: boolean; missing: string[] }; expiresAt: string };
type RunTarget = { id: string; contactId: string; state: string; snapshot: { contact: { name: string } }; attempts: { id: string; attemptNo: number; callState: string; identityState: string; ackState: string; recognitionState: string; responses: { outcome: { classification: string; phoneConfirmed: boolean; requiresStaff: boolean; reasons: string[] }; answers: Record<string, Answer> }[] }[]; cases: { id: string; status: string }[] };
export function MunicipalWorkflowPanel(props: OutreachPanelProps) {
  const { permissions, setDirty: setParentDirty, setSaving } = props, { t, locale } = useI18n(), w = t.municipalWorkflows, d = t.outreachCommon, m = t.municipalOutreach, z = t.admin.zaad;
  const query = useSearchParams(), router = useRouter(), purpose = MUNICIPAL_PURPOSES.find(value => purposePath[value] === query.get("workflow")) ?? "ELDER_WATCH", step = query.get("step") ?? "targets", workflowId = query.get("workflowId"), runId = query.get("runId");
  const [workflows, setWorkflows] = useState<Workflow[] | null>(null), [workflow, setWorkflow] = useState<Workflow | null>(null), [contacts, setContacts] = useState<ContactDto[]>([]), [targets, setTargets] = useState<Target[]>([]), [assignees, setAssignees] = useState<Assignee[]>([]), [flows, setFlows] = useState<{ id: string; name: string }[]>([]);
  const [failure, setFailure] = useState(false), [reload, setReload] = useState(0), [busy, setBusyState] = useState(false), [error, setError] = useState(""), [editingTarget, setEditingTarget] = useState<ContactDto | null>(null), [selected, setSelected] = useState<string[]>([]), [preview, setPreview] = useState<Preview | null>(null), [run, setRun] = useState<RunResult | null>(null);
  const [draftTargets, setDraftTargets] = useState<DraftTarget[]>([]);
  const dirtyRef = useRef(false), targetDirty = useRef(false);
  const [pendingNavigation, setPendingNavigation] = useState<(() => void) | null>(null);
  const setDirty = (value: boolean) => { dirtyRef.current = value; setParentDirty(value); };
  const navigate = (action: () => void) => { if (lock.current) return; if (dirtyRef.current || targetDirty.current) setPendingNavigation(() => action); else action(); };
  const closeTarget = () => navigate(() => { targetDirty.current = false; setEditingTarget(null); });
  const operation = useRef<string | null>(null), lock = useRef(false);
  const setBusy = (value: boolean) => { setBusyState(value); setSaving?.(value); };
  useEffect(() => {
    const controller = new AbortController();
    Promise.all([outreachRequest<ListResult<Workflow>>("lg", "municipal/workflows", { signal: controller.signal }), outreachAll<ContactDto>("lg", "contacts", { signal: controller.signal }), outreachRequest<ListResult<Assignee>>("lg", "municipal/assignees", { signal: controller.signal }), outreachRequest<ListResult<{ id: string; name: string }>>("lg", "flows", { signal: controller.signal })]).then(async ([list, people, staff, flowList]) => {
      if (controller.signal.aborted) return;
      setWorkflows(list.items.filter(row => row.purpose === purpose)); setContacts(people.filter(row => row.reference.origin === "MUNICIPAL_CONTACT")); setAssignees(staff.items); setFlows(flowList.items);
      const current = list.items.find(row => row.workflowId === workflowId && row.purpose === purpose);
      setWorkflow(current ?? null);
      if (current) { const result = await outreachRequest<{ items: Target[] }>("lg", `municipal/workflows/${encodeURIComponent(current.workflowId)}/targets`, { signal: controller.signal }); if (!controller.signal.aborted) setTargets(result.items); } else setTargets([]);
      if (runId) { const result = await outreachRequest<{ run: RunResult }>("lg", `municipal/runs/${encodeURIComponent(runId)}`, { signal: controller.signal }); if (!controller.signal.aborted) setRun(result.run); } else setRun(null);
    }).catch(() => { if (!controller.signal.aborted) setFailure(true); });
    return () => controller.abort();
  }, [purpose, workflowId, runId, reload]);
  function go(next: string, extra: Record<string, string | null> = {}, onNavigate?: () => void) { const params = new URLSearchParams(query.toString()); params.set("view", purpose === "FRAUD_ALERT" ? "one-time" : "campaigns"); params.set("step", next); for (const [key, value] of Object.entries(extra)) { if (value === null) params.delete(key); else params.set(key, value); } navigate(() => { onNavigate?.(); router.push(`/admin/zaad?${params}`, { scroll: false }); }); }
  async function saveSetup(form: FormData) {
    if (lock.current) return; lock.current = true; setBusy(true); setError("");
    try { const str = (name: string) => String(form.get(name) ?? ""), result = await outreachMutation<{ workflow: Workflow; targets: { id: string; excluded: boolean }[] }>("lg", workflow ? `municipal/workflows/${encodeURIComponent(workflow.workflowId)}` : "municipal/workflows", { ...(workflow ? { version: workflow.revision } : { initialTargets: draftTargets }), name: str("name"), purpose, body: str("body"), voiceId: str("voice"), questionVersion: QUESTION_VERSION, schedule: municipalTimeValues(form, "schedule"), maxRetries: Number(str("maxRetries")), retryIntervalMinutes: Number(str("retryIntervalMinutes")), assigneeId: str("assignee"), dueAt: new Date(`${str("dueAt")}:00+09:00`).toISOString(), flowBindingId: str("flow") || null }, workflow ? "PATCH" : "POST"); setDirty(false); setDraftTargets([]); if (result.targets.length) setSelected(result.targets.filter(row => !row.excluded).map(row => row.id)); setWorkflow(result.workflow); setReload(value => value + 1); lock.current = false; go("targets", { workflowId: result.workflow.workflowId }); }
    catch { setError(z.common.failure); } finally { lock.current = false; setBusy(false); }
  }
  async function saveTarget(evidence: unknown, excluded: boolean) { if (!editingTarget || lock.current) return; if (!workflow) { setDraftTargets(current => [...current.filter(row => row.contactId !== editingTarget.reference.id), { contactId: editingTarget.reference.id, businessEvidence: evidence, excluded }]); targetDirty.current = false; setDirty(true); setEditingTarget(null); return; } lock.current = true; setBusy(true); setError(""); try { const existing = targets.find(row => row.contactId === editingTarget.reference.id); await outreachMutation("lg", `municipal/workflows/${encodeURIComponent(workflow.workflowId)}/targets`, { version: workflow.revision, contactId: editingTarget.reference.id, targetVersion: existing?.version ?? 0, businessEvidence: evidence, excluded }); targetDirty.current = false; setDirty(false); setEditingTarget(null); setReload(value => value + 1); } catch { setError(z.common.failure); } finally { lock.current = false; setBusy(false); } }
  async function review() { if (!workflow || lock.current) return; lock.current = true; setBusy(true); setError(""); operation.current ??= crypto.randomUUID(); try { const result = await outreachMutation<Preview>("lg", `municipal/workflows/${encodeURIComponent(workflow.workflowId)}/preview`, { version: workflow.revision, selection: selected, operationKey: operation.current }); setPreview(result); } catch { setError(z.common.failure); } finally { lock.current = false; setBusy(false); } }
  const boundary = purpose === "ELDER_WATCH" ? w.watchBoundary : purpose === "PROCEDURE_SUPPORT" ? w.procedureBoundary : purpose === "SERVICE_CONFIRMATION" ? w.serviceBoundary : w.fraudBoundary;
  const questions = purpose === "ELDER_WATCH" ? [w.usualQuestion, w.callbackQuestion] : purpose === "PROCEDURE_SUPPORT" ? [w.deliveredQuestion, w.submissionQuestion, w.helpQuestion] : purpose === "SERVICE_CONFIRMATION" ? [w.attendanceQuestion, w.callbackQuestion] : [w.ackQuestion, w.similarQuestion, w.consultQuestion];
  const questionLabels: Record<string, string> = { usual: w.usualQuestion, callback: w.callbackQuestion, delivered: w.deliveredQuestion, submission: w.submissionQuestion, help: w.helpQuestion, attendance: w.attendanceQuestion, ack: w.ackQuestion, similar: w.similarQuestion, consult: w.consultQuestion };
  if (failure) return <OutreachFailure retry={() => { setFailure(false); setReload(value => value + 1); }} />;
  if (!workflows) return <OutreachLoading />;
  if (step === "cases") return <MunicipalCases {...props} purpose={query.has("workflow") ? purpose : undefined} />;
  return <section className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">{m.topics[purposeTopic[purpose]]}</h2><button className={secondary} onClick={() => { const params = new URLSearchParams({ tenant: "lg", view: purpose === "FRAUD_ALERT" ? "one-time" : "campaigns" }); navigate(() => router.push(`/admin/zaad?${params}`)); }}>{z.common.previous}</button></div><p className="text-sm leading-7 text-fg-muted">{boundary}</p><nav aria-label={d.workflow} className="flex flex-wrap gap-2">{["targets", "setup", "results", "cases"].map((value, index) => <button key={value} aria-current={step === value ? "step" : undefined} className={step === value ? primary : secondary} onClick={() => go(value)}>{d.steps[index]}</button>)}</nav>{error && <p role="alert">{error}</p>}
    <div className="flex flex-wrap items-end gap-3"><label className="min-w-0 flex-1">{w.existing}<Select value={workflowId ?? ""} onChange={event => { go(step, { workflowId: event.target.value || null, runId: null }, () => { setSelected([]); setDraftTargets([]); operation.current = null; }); }}><option value="">{m.choose}</option>{workflows.map(row => <option key={row.workflowId} value={row.workflowId}>{row.name}</option>)}</Select></label>{permissions.create && <button className={secondary} onClick={() => navigate(() => { setWorkflow(null); setDraftTargets([]); setSelected([]); setDirty(false); go("targets", { workflowId: null, runId: null }); })}>{w.newWorkflow}</button>}</div>
    {step === "targets" && <div className="space-y-4">{!workflow ? <><p>{d.selected}: {draftTargets.filter(row => !row.excluded).length}</p><div className="divide-y divide-line rounded-lg border border-line">{contacts.map(contact => <div key={contact.reference.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><span>{contact.name}<span className="block text-xs text-fg-muted">{draftTargets.some(row => row.contactId === contact.reference.id && !row.excluded) ? w.targetEntered : w.unconfirmed}</span></span><button className={secondary} disabled={!permissions.create} aria-label={`${contact.name}: ${w.businessRecord}`} onClick={() => setEditingTarget(contact)}>{w.businessRecord}</button></div>)}</div><button className={primary} disabled={!draftTargets.length || !permissions.create} onClick={() => { const params = new URLSearchParams(query.toString()); params.set("view", purpose === "FRAUD_ALERT" ? "one-time" : "campaigns"); params.set("step", "setup"); router.push(`/admin/zaad?${params}`, { scroll: false }); }}>{d.steps[1]}</button></> : <><p role="status">{d.selected}: {selected.length}</p><div className="divide-y divide-line rounded-lg border border-line">{contacts.map(contact => { const target = targets.find(row => row.contactId === contact.reference.id); return <div key={contact.reference.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><label className="flex items-center gap-3"><Checkbox checked={Boolean(target && selected.includes(target.id))} disabled={!target?.eligible || busy} onChange={event => { operation.current = null; setSelected(current => event.target.checked ? [...current, target!.id] : current.filter(id => id !== target!.id)); }} /><span>{contact.name}<span className="block text-xs text-fg-muted">{target?.eligible ? w.eligible : w.unconfirmed}</span>{target?.reasons.map(reason => <span key={reason} className="block text-xs text-fg-muted">{w.labels[reason] ?? w.unknown}</span>)}</span></label>{permissions.update && <button className={secondary} aria-label={`${contact.name}: ${w.businessRecord}`} onClick={() => setEditingTarget(contact)}>{w.businessRecord}</button>}</div>; })}</div>{!contacts.length && <p>{z.common.empty}</p>}<button className={primary} disabled={busy || !selected.length || !permissions.create} onClick={() => void review()}>{d.preview}</button></>}</div>}
    {step === "setup" && <form key={workflow?.id ?? purpose} className="max-w-3xl space-y-5" onChange={() => setDirty(true)} onSubmit={event => { event.preventDefault(); void saveSetup(new FormData(event.currentTarget)); }}><fieldset disabled={busy || !(workflow ? permissions.update : permissions.create)} className="space-y-5"><label className="block">{z.messages.name}<input required name="name" className={input} defaultValue={workflow?.name ?? m.topics[purposeTopic[purpose]]} maxLength={100} /></label><label className="block">{z.messages.body}<textarea required name="body" rows={4} className={input} maxLength={500} defaultValue={workflow?.settings.body} /></label><label className="block">{z.messages.voice}<Select name="voice" defaultValue={workflow?.settings.voiceId ?? "Takumi"}>{OUTREACH_VOICES.map(voice => <option key={voice}>{voice}</option>)}</Select></label><section className="rounded-lg border border-line p-4"><h3 className="font-semibold">{w.questions}</h3><ol className="mt-3 list-inside list-decimal space-y-2 text-sm">{questions.map(question => <li key={question}>{question}</li>)}</ol></section><MunicipalTimeFields prefix="schedule" value={workflow?.settings.schedule} /><div className="grid gap-4 sm:grid-cols-2"><label>{w.maxRetries}<input className={input} type="number" name="maxRetries" min={0} max={3} required defaultValue={workflow?.settings.maxRetries ?? 0} /></label><label>{w.retryInterval}<input className={input} type="number" name="retryIntervalMinutes" min={5} max={1440} required defaultValue={workflow?.settings.retryIntervalMinutes ?? 60} /></label></div><label className="block">{w.assignee}<Select required name="assignee" defaultValue={workflow?.assigneeId ?? ""}><option value="">{m.choose}</option>{assignees.map(person => <option key={person.id} value={person.id}>{person.name}</option>)}</Select></label><label className="block">{w.deadline}<input className={input} name="dueAt" type="datetime-local" required defaultValue={workflow?.dueAt ? new Date(new Date(workflow.dueAt).getTime() + 9 * 3600000).toISOString().slice(0, 16) : undefined} /></label><label className="block">{d.flow}<Select name="flow" defaultValue={workflow?.settings.flowBindingId ?? ""}><option value="">{m.choose}</option>{flows.map(flow => <option key={flow.id} value={flow.id}>{flow.name}</option>)}</Select></label><p className="text-sm text-fg-muted">{d.flowGate}</p></fieldset><button className={primary} disabled={busy || !(workflow ? permissions.update : permissions.create)}>{z.common.save}</button></form>}
    {step === "results" && <section className="space-y-4"><p className="text-sm text-fg-muted">{w.phoneOnly}</p>{!run ? <p>{w.resultsEmpty}</p> : <><div className="flex flex-wrap gap-5 rounded-lg border border-line p-4"><span>{w.eligible}: {run.targets.length}</span><span>{w.attempts}: {run.targets.reduce((sum, row) => sum + row.attempts.length, 0)}</span><span>{w.confirmed}: {run.targets.filter(row => row.attempts.some(attempt => attempt.responses.some(response => response.outcome.phoneConfirmed))).length}</span><span>{w.staffRequired}: {run.targets.filter(row => row.cases.length > 0).length}</span></div>{run.targets.map(target => <article key={target.id} className="space-y-3 rounded-lg border border-line p-4"><h3 className="font-semibold">{target.snapshot.contact.name}</h3>{!target.attempts.length && <p className="text-sm text-fg-muted">{w.resultsEmpty}</p>}{target.attempts.map(attempt => <section key={attempt.id} className="space-y-3 border-t border-line pt-3"><p className="text-sm font-semibold">{w.attempts}: {attempt.attemptNo}</p><dl className="grid gap-2 text-sm sm:grid-cols-2">{[[w.phoneState, attempt.callState], [w.identityState, attempt.identityState], [w.recognitionState, attempt.recognitionState], [w.ackState, attempt.ackState]].map(([label, value]) => <div key={label}><dt className="text-fg-muted">{label}</dt><dd>{d.stateLabels[value] ?? d.unknown}</dd></div>)}</dl>{attempt.responses.map((response, index) => <section key={index} className="space-y-2 text-sm"><p className="font-semibold">{w.labels[response.outcome.classification] ?? w.unknown}</p>{response.outcome.reasons.length > 0 && <ul className="list-inside list-disc">{response.outcome.reasons.map(reason => <li key={reason}>{w.labels[reason] ?? w.unknown}</li>)}</ul>}<dl className="space-y-2">{Object.entries(questionLabels).filter(([key]) => response.answers[key]).map(([key, label]) => <div key={key}><dt className="text-fg-muted">{label}</dt><dd>{w.labels[response.answers[key].value] ?? w.unknown} · {w.labels[response.answers[key].input] ?? w.unknown}</dd></div>)}</dl></section>)}</section>)}{target.cases.length > 0 && <button className={secondary} onClick={() => go("cases", { caseId: target.cases[0].id })}>{d.staffCases}</button>}</article>)}</>}</section>}
    {step === "results" && run && <section aria-label={w.eventIssuesTitle} className="space-y-3 border-t border-line pt-4"><h3 className="font-semibold">{w.eventIssuesTitle}</h3><p className="text-sm text-fg-muted">{w.eventIssuesHelp}</p>{run.eventIssues.length ? <><p className="text-sm text-fg-muted">{w.eventIssuesLimit}</p><ul className="space-y-3">{run.eventIssues.map(issue => <li key={issue.id} className="rounded-md border border-line p-3 text-sm"><p>{w.eventIssueReason}: {w.labels[issue.errorCode ?? ""] ?? w.unknown}</p><p>{w.eventReceivedAt}: {new Date(issue.receivedAt).toLocaleString(locale, { timeZone: "Asia/Tokyo" })}</p></li>)}</ul></> : <p className="text-sm">{w.eventIssuesEmpty}</p>}</section>}
    {editingTarget && <ModalDialog title={w.businessRecord} description={boundary} locked={busy || pendingNavigation !== null} onRequestClose={closeTarget} maxWidthClassName="max-w-2xl">{error && <p role="alert">{error}</p>}<MunicipalTargetForm initial={workflow ? targets.find(row => row.contactId === editingTarget.reference.id) : draftTargets.find(row => row.contactId === editingTarget.reference.id)} onDirty={() => { targetDirty.current = true; setDirty(true); }} contact={editingTarget} purpose={purpose} busy={busy} save={(evidence, excluded) => void saveTarget(evidence, excluded)} cancel={closeTarget} /></ModalDialog>}
    {preview && <ModalDialog title={w.reviewReady} description={boundary} onRequestClose={() => setPreview(null)}><div className="space-y-4"><p>{w.eligible}: {preview.eligible}</p><p>{w.excluded}: {preview.excluded.length}</p><p className="text-sm text-fg-muted">{w.blocked}</p><ul className="list-inside list-disc space-y-1 text-sm">{preview.readiness.missing.map(reason => <li key={reason}>{w.labels[reason] ?? w.unknown}</li>)}</ul>{preview.excluded.map(target => <section key={target.id} className="text-sm"><p className="font-semibold">{target.name}</p><ul className="list-inside list-disc">{target.reasons.map(reason => <li key={reason}>{w.labels[reason] ?? w.unknown}</li>)}</ul></section>)}<div className="flex flex-wrap gap-3"><button className={secondary} onClick={() => { go("results", { runId: preview.snapshotId }); setPreview(null); }}>{d.steps[2]}</button><button className={primary} disabled>{d.preview}</button></div></div></ModalDialog>}
    {pendingNavigation && <ModalDialog title={d.confirmDiscard} description={d.workflow} onRequestClose={() => setPendingNavigation(null)}><div className="flex justify-end gap-3"><button className={secondary} onClick={() => setPendingNavigation(null)}>{z.common.cancel}</button><button className={primary} onClick={() => { const action = pendingNavigation; setPendingNavigation(null); targetDirty.current = false; setDirty(false); action(); }}>{d.discard}</button></div></ModalDialog>}
  </section>;
}
