"use client";
import { Feedback } from "@/app/components/admin/Feedback";
import { DetailPageBreadcrumb } from "./DetailPageBreadcrumb";
import { useCallback, useEffect, useRef, useState } from "react";
import { useI18n } from "@/app/i18n/LanguageProvider";
import { Select } from "@/app/components/Select";
import { Checkbox } from "@/app/components/Checkbox";
import { ModalDialog } from "@/app/components/admin/ModalDialog";
import { OUTREACH_VOICES } from "@/lib/zaad/message-contracts";
import { type ContactDto, referenceKey } from "@/lib/zaad/outreach-contracts";
import { MUNICIPAL_TOPICS } from "@/lib/zaad/municipal/contracts";
import { TOPICS } from "@/lib/zaad/university/contracts";
import { outreachAll, outreachMutation, outreachRequest, type ListResult } from "./outreach-client";
import { type OutreachPanelProps } from "./OutreachView";
import { registrationInputClass as input, outreachPrimary as primary, outreachSecondary as secondary } from "@/app/notifications/register/StudentNotificationRegistration";
import type { DispatchRecord } from "@/app/admin/zaad/outreach-dispatch-types";
type Message = { id: string; name: string; body: string; voiceId: string; languageCode: string; currentRevisionId: string | null; revisions?: { id: string; body: string; voiceId: string; languageCode: string }[] };
type Group = { id: string; name: string };
export function OutreachDispatchEditor({ tenant, permissions, setDirty, setSaving, record, rerun, close, confirmed }: OutreachPanelProps & { record: DispatchRecord | null; rerun: boolean; close: () => void; confirmed: (id: string) => void }) {
  const { t } = useI18n(), d = t.outreachCommon, z = t.admin.zaad, u = d.dispatchUi;
  const initial = record?.draft;
  const [busy, setBusyState] = useState(false), [error, setError] = useState("");
  const [messages, setMessages] = useState<Message[]>([]), [groups, setGroups] = useState<Group[]>([]), [people, setPeople] = useState<ContactDto[]>([]), [flows, setFlows] = useState<Group[]>([]);
  const [name, setName] = useState(initial?.name ?? ""), [body, setBody] = useState(initial?.body ?? ""), [voice, setVoice] = useState<string>(initial?.voiceId ?? "Tomoko"), [connectionMode, setConnectionMode] = useState<string>(initial?.connectionMode ?? "MEDIA"), [messageMode, setMessageMode] = useState(initial?.messageRevisionId && record?.messageRevision ? "SAVED" : "DIRECT"), [messageRevision, setMessageRevision] = useState<string | null>(initial?.messageRevisionId ?? null), [flow, setFlow] = useState(initial?.flowBindingId ?? ""), [targetMode, setTargetMode] = useState<string>(initial?.targetMode ?? "PEOPLE"), [selected, setSelected] = useState<string[]>(initial ? initial.targetMode === "GROUPS" ? initial.groupIds : initial.people.map(referenceKey) : []), [topic, setTopic] = useState(initial?.topic ?? "");
  const [flowGuide, setFlowGuide] = useState(false);
  const operation = useRef<string | null>(null), lock = useRef(false), cancel = useRef<HTMLButtonElement>(null), nameInput = useRef<HTMLInputElement>(null);
  const [discard, setDiscard] = useState(false), [loadingChoices, setLoadingChoices] = useState(true), [choicesFailed, setChoicesFailed] = useState(false), [loadingMessage, setLoadingMessage] = useState(false);
  const parentDispatchId = rerun ? record?.id ?? null : initial?.parentDispatchId ?? null;
  const [pendingMessage, setPendingMessage] = useState<string | null>(null), [messageId, setMessageId] = useState(record?.messageRevision?.messageId ?? "");
  const hasDirty = useRef(false), generation = useRef(0), messageGeneration = useRef(0);
  useEffect(() => () => { generation.current++; messageGeneration.current++; }, []);
  const setBusy = (value: boolean) => { setBusyState(value); setSaving?.(value); };
  const dirty = () => { hasDirty.current = true; operation.current = null; setDirty(true); };
  const loadChoices = useCallback(() => {
    const ticket = ++generation.current;
    return Promise.all([outreachRequest<ListResult<Message>>(tenant, "messages"), outreachRequest<ListResult<Group>>(tenant, "contact-lists"), outreachAll<ContactDto>(tenant, "contacts"), outreachRequest<ListResult<Group>>(tenant, "flows")])
      .then(([m, g, p, f]) => { if (ticket === generation.current) { setMessages(m.items); setGroups(g.items); setPeople(p); setFlows(f.items); setChoicesFailed(false); setError(""); } })
      .catch(() => { if (ticket === generation.current) { setChoicesFailed(true); setError(z.common.failure); } })
      .finally(() => { if (ticket === generation.current) setLoadingChoices(false); });
  }, [tenant, z.common.failure]);
  async function chooseMessage(id: string) { if (!permissions.create || lock.current) return; setPendingMessage(null); const ticket = ++messageGeneration.current; setError(""); setLoadingMessage(false); if (!id) { setMessageId(""); setMessageRevision(null); dirty(); return; } setLoadingMessage(true); try { const message = await outreachRequest<Message>(tenant, `messages/${encodeURIComponent(id)}`), revision = message.revisions?.find(snapshot => snapshot.id === message.currentRevisionId); if (!revision) throw new Error("NO_REVISION"); if (ticket !== messageGeneration.current) return; dirty(); setMessageId(id); setMessageRevision(revision.id); setBody(revision.body); setVoice(revision.voiceId); } catch { if (ticket === messageGeneration.current) setError(z.common.failure); } finally { if (ticket === messageGeneration.current) setLoadingMessage(false); } }
  async function preflight() { if (lock.current || !permissions.create || loadingChoices || choicesFailed || loadingMessage || (connectionMode === "MEDIA" && messageMode === "SAVED" && !messageRevision)) return; lock.current = true; setBusy(true); setError(""); operation.current ??= crypto.randomUUID(); try { const result = await outreachMutation<{ id: string }>(tenant, "one-time-dispatches/preflight", { operationKey: operation.current, parentDispatchId, name, body, voiceId: voice, languageCode: "ja-JP", connectionMode, messageRevisionId: messageMode === "SAVED" ? messageRevision : null, flowBindingId: connectionMode === "FLOW" ? flow : null, targetMode, groupIds: targetMode === "GROUPS" ? selected : [], people: targetMode === "PEOPLE" ? people.filter(person => selected.includes(referenceKey(person.reference))).map(person => person.reference) : [], topic }); hasDirty.current = false; setDirty(false); confirmed(result.id); } catch { setError(z.oneTime.invalid); } finally { lock.current = false; setBusy(false); } }
  useEffect(() => { void loadChoices(); }, [loadChoices]);
  useEffect(() => { if (!loadingChoices && !choicesFailed && permissions.create) nameInput.current?.focus(); }, [loadingChoices, choicesFailed, permissions.create]);
  function finish() { if (lock.current) return; generation.current++; messageGeneration.current++; hasDirty.current = false; setDirty(false); close(); }
  function requestClose() { if (lock.current) return; if (hasDirty.current) setDiscard(true); else finish(); }
  return <section className="max-w-4xl space-y-6" aria-labelledby="dispatch-page-title"><div className="flex flex-wrap items-center justify-between gap-3"><h1 id="dispatch-page-title" className="text-2xl font-bold">{record?.name ?? u.createTitle}</h1></div><DetailPageBreadcrumb title={record?.name ?? u.createTitle} disabled={busy} />
    {error && <Feedback tone="error" action={choicesFailed && <button className={secondary} disabled={busy || loadingChoices} onClick={() => { setLoadingChoices(true); setChoicesFailed(false); void loadChoices(); }}>{z.common.retry}</button>}>{error}</Feedback>}
<form className="space-y-5" aria-busy={busy || loadingChoices || loadingMessage} onSubmit={event => { event.preventDefault(); void preflight(); }}><fieldset disabled={busy || loadingChoices || loadingMessage || !permissions.create} className="space-y-5"><legend className="sr-only">{u.createTitle}</legend><label className="block">{d.groupName}<input ref={nameInput} className={input} required maxLength={100} value={name} onChange={event => { setName(event.target.value); dirty(); }} /></label><label className="block">{u.connection}<Select value={connectionMode} onChange={event => { messageGeneration.current++; setLoadingMessage(false); setConnectionMode(event.target.value); dirty(); }}><option value="MEDIA">{d.media}</option><option value="FLOW">{d.flow}</option></Select></label>
    {connectionMode === "MEDIA" ? <><label className="block">{u.messageMethod}<Select value={messageMode} onChange={event => { messageGeneration.current++; setLoadingMessage(false); setMessageMode(event.target.value); setMessageRevision(null); dirty(); }}><option value="DIRECT">{d.direct}</option><option value="SAVED">{d.savedMessage}</option></Select></label>{messageMode === "SAVED" && <label className="block">{d.savedMessage}<Select required value={messageId} onChange={event => { const id = event.target.value; if (id && body.trim()) setPendingMessage(id); else void chooseMessage(id); }}><option value="">{t.municipalOutreach.choose}</option>{messages.map(message => <option key={message.id} value={message.id}>{message.name}</option>)}</Select></label>}</> : <label className="block">{d.flow}<Select required value={flow} onChange={event => { setFlow(event.target.value); dirty(); }}><option value="">{t.municipalOutreach.choose}</option>{flows.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><span className="mt-2 block text-sm text-fg-muted">{d.flowGate}</span></label>}
    {connectionMode === "FLOW" && <button type="button" className={secondary} onClick={() => setFlowGuide(true)}>{u.flowGuideButton}</button>}
    {connectionMode === "MEDIA" && messageMode === "SAVED" && messageId && <div className="flex flex-wrap items-center gap-3"><button type="button" className={secondary} onClick={() => setPendingMessage(messageId)}>{u.importLatest}</button></div>}
    <label className="block">{z.messages.body}<textarea required maxLength={2000} rows={5} className={input} readOnly={connectionMode === "MEDIA" && messageMode === "SAVED"} value={body} onChange={event => { setBody(event.target.value); dirty(); }} /></label><label className="block">{z.messages.voice}<Select disabled={connectionMode === "MEDIA" && messageMode === "SAVED"} value={voice} onChange={event => { setVoice(event.target.value); dirty(); }}>{OUTREACH_VOICES.map(value => <option key={value}>{value}</option>)}</Select></label><label className="block">{u.target}<Select value={targetMode} onChange={event => { setTargetMode(event.target.value); setSelected([]); dirty(); }}><option value="PEOPLE">{d.people}</option><option value="GROUPS">{d.groups}</option></Select></label><div className="max-h-56 space-y-3 overflow-y-auto rounded-md border border-line p-3">{(targetMode === "PEOPLE" ? people.map(person => ({ id: referenceKey(person.reference), name: person.name })) : groups).map(item => <label key={item.id} className="flex gap-3"><Checkbox checked={selected.includes(item.id)} onChange={event => { setSelected(current => event.target.checked ? [...current, item.id] : current.filter(id => id !== item.id)); dirty(); }} />{item.name}</label>)}</div><label className="block">{d.topic}<Select required value={topic} onChange={event => { setTopic(event.target.value); dirty(); }}><option value="">{t.municipalOutreach.choose}</option>{tenant === "lg" && <option value="disaster-radio">{d.disasterTopic}</option>}{(tenant === "lg" ? MUNICIPAL_TOPICS : TOPICS).map((value, index) => <option key={value} value={value}>{tenant === "lg" ? t.municipalOutreach.topics[value] : t.universityOutreach.topicLabels[index]}</option>)}</Select></label></fieldset><div className="flex justify-end gap-3"><button type="button" className={secondary} disabled={busy} onClick={requestClose}>{z.common.cancel}</button><button className={primary} disabled={busy || loadingChoices || choicesFailed || loadingMessage || !permissions.create || !selected.length || (connectionMode === "MEDIA" && messageMode === "SAVED" && !messageRevision)}>{busy ? z.oneTime.preflight : u.confirm}</button></div></form>
    {flowGuide && <ModalDialog initialFocusRef={cancel} title={u.flowGuideTitle} description={d.flowGate} onRequestClose={() => setFlowGuide(false)}><ol className="list-decimal space-y-3 pl-5 text-sm leading-7">{u.flowGuideSteps.map(step => <li key={step}>{step}</li>)}</ol><div className="mt-6 flex justify-end"><button ref={cancel} className={secondary} onClick={() => setFlowGuide(false)}>{z.common.close}</button></div></ModalDialog>}
    {pendingMessage !== null && <ModalDialog initialFocusRef={cancel} title={d.replaceMessage} description={d.savedMessage} onRequestClose={() => setPendingMessage(null)}><div className="flex justify-end gap-3"><button ref={cancel} className={secondary} onClick={() => setPendingMessage(null)}>{z.common.cancel}</button><button className={primary} onClick={() => void chooseMessage(pendingMessage)}>{z.common.confirm}</button></div></ModalDialog>}
    {discard && <ModalDialog initialFocusRef={cancel} title={d.confirmDiscard} description={name} onRequestClose={() => setDiscard(false)}><div className="flex justify-end gap-3"><button ref={cancel} className={secondary} onClick={() => setDiscard(false)}>{z.common.cancel}</button><button className={primary} onClick={finish}>{d.discard}</button></div></ModalDialog>}
  </section>;
}
