"use client";
import { Feedback } from "@/app/components/admin/Feedback";
import { useEffect, useRef, useState } from "react";
import { useI18n } from "@/app/i18n/LanguageProvider";
import { Select } from "@/app/components/Select";
import { ModalDialog } from "@/app/components/admin/ModalDialog";
import type { ContactDto } from "@/lib/zaad/outreach-contracts";
import { outreachMutation, outreachRequest } from "./outreach-client";
import { OutreachFailure, OutreachLoading, type OutreachPanelProps } from "./OutreachView";
import { registrationInputClass as input, outreachPrimary as primary, outreachSecondary as secondary } from "@/app/notifications/register/StudentNotificationRegistration";
type Legacy = ContactDto & { legacyRecord: { email: string; consentStatus: string; revision: number; syncStatus: string } };
export function OutreachLegacyContactEditor({ contact, close, saved, ...props }: OutreachPanelProps & { contact: ContactDto; close: () => void; saved: () => void }) {
  const { t } = useI18n(), d = t.outreachCommon, z = t.admin.zaad;
  const [detail, setDetail] = useState<Legacy | null>(null), [reload, setReload] = useState(0), [failed, setFailed] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(""), [discard, setDiscard] = useState(false), [deleting, setDeleting] = useState(false);
  const dirty = useRef(false), lock = useRef(false);
  useEffect(() => { const controller = new AbortController(); outreachRequest<{ contact: Legacy }>(props.tenant, `contacts/${encodeURIComponent(contact.reference.id)}?origin=DISASTER_RADIO`, { signal: controller.signal }).then(result => { if (!controller.signal.aborted) setDetail(result.contact); }).catch(() => { if (!controller.signal.aborted) setFailed(true); }); return () => controller.abort(); }, [props.tenant, contact.reference.id, reload]);
  const finish = () => { props.setDirty(false); close(); };
  const requestClose = () => { if (lock.current) return; if (dirty.current) setDiscard(true); else finish(); };
  async function submit(form?: FormData) {
    if (lock.current || !detail) return; lock.current = true; setBusy(true); props.setSaving?.(true); setError("");
    try { await outreachMutation(props.tenant, `contacts/${encodeURIComponent(contact.reference.id)}/legacy`, form ? { name: form.get("name"), email: form.get("email"), phone: form.get("phone"), consentStatus: form.get("consentStatus"), revision: detail.legacyRecord.revision } : { revision: detail.legacyRecord.revision }, form ? "PATCH" : "DELETE"); props.setDirty(false); saved(); }
    catch { setError(z.residents.formInvalid); } finally { lock.current = false; setBusy(false); props.setSaving?.(false); }
  }
  return <><ModalDialog title={z.residents.editTitle} description={d.legacyHelp} locked={busy || discard || deleting} onRequestClose={requestClose}>{failed ? <OutreachFailure retry={() => { setFailed(false); setReload(value => value + 1); }} /> : !detail ? <OutreachLoading /> : <form className="space-y-4" onChange={() => { dirty.current = true; props.setDirty(true); }} onSubmit={event => { event.preventDefault(); void submit(new FormData(event.currentTarget)); }}>{error && !deleting && <Feedback tone="error">{error}</Feedback>}<fieldset disabled={busy || !props.permissions.update} className="space-y-4">{[["name", z.residents.name, detail.name, "text"], ["email", z.residents.email, detail.legacyRecord.email, "email"], ["phone", z.residents.phone, detail.phone, "tel"]].map(([name, label, value, type]) => <label className="block" key={name}>{label}<input className={input} name={name} type={type} required defaultValue={value} /></label>)}<label className="block">{z.residents.consent}<Select name="consentStatus" defaultValue={detail.legacyRecord.consentStatus}><option value="CONSENTED">{z.residents.consentedValue}</option><option value="NOT_CONSENTED">{z.residents.notConsentedValue}</option></Select></label></fieldset><div className="flex flex-wrap justify-end gap-3">{props.permissions.delete && <button type="button" className={secondary} disabled={busy} onClick={() => { setError(""); setDeleting(true); }}>{z.common.delete}</button>}<button type="button" className={secondary} disabled={busy} onClick={requestClose}>{z.common.cancel}</button>{props.permissions.update && <button className={primary} disabled={busy}>{z.common.save}</button>}</div></form>}</ModalDialog>{deleting && <ModalDialog title={z.residents.deleteTitle} description={contact.name} locked={busy} onRequestClose={() => { if (!lock.current) setDeleting(false); }}>{error && <Feedback tone="error" className="mb-4">{error}</Feedback>}<p className="mb-4 text-sm">{z.residents.deleteDescription}</p><div className="flex justify-end gap-3"><button className={secondary} disabled={busy} onClick={() => setDeleting(false)}>{z.common.cancel}</button><button className={primary} disabled={busy} onClick={() => void submit()}>{z.common.delete}</button></div></ModalDialog>}{discard && <ModalDialog title={d.confirmDiscard} description={contact.name} onRequestClose={() => setDiscard(false)}><div className="flex justify-end gap-3"><button className={secondary} onClick={() => setDiscard(false)}>{z.common.cancel}</button><button className={primary} onClick={finish}>{d.discard}</button></div></ModalDialog>}</>;
}
