"use client";
import { Feedback } from "@/app/components/admin/Feedback";
import { useEffect, useRef, useState } from "react";
import { useI18n } from "@/app/i18n/LanguageProvider";
import { Checkbox } from "@/app/components/Checkbox";
import { Select } from "@/app/components/Select";
import { ModalDialog } from "@/app/components/admin/ModalDialog";
import { type ContactDto } from "@/lib/zaad/outreach-contracts";
import { MUNICIPAL_CONSENT_VERSION, MUNICIPAL_TOPICS, type Availability } from "@/lib/zaad/municipal/contracts";
import { CONSENT_VERSION, TOPICS } from "@/lib/zaad/university/contracts";
import { outreachMutation, outreachRequest } from "./outreach-client";
import { OutreachFailure, OutreachLoading, type OutreachPanelProps } from "./OutreachView";
import { RegistrationFields, emptyRegistration, registrationPayload, registrationInputClass as input, outreachPrimary as primary, outreachSecondary as secondary } from "@/app/notifications/register/StudentNotificationRegistration";
type Detail = ContactDto & { registration?: { note?: string; contact: { id: string; version: number } | null }; attestation?: string; availability?: { requested: Availability; confirmed: Availability | null } | null };
export function OutreachContactEditor({ tenant, permissions, contact, close, edit, saved, setDirty, setSaving, years, initialMode = "edit" }: OutreachPanelProps & { initialMode?: "detail" | "edit"; contact: ContactDto | null; edit: () => void; close: () => void; saved: () => void }) {
  const { t } = useI18n(), d = t.outreachCommon, m = t.municipalOutreach, u = t.universityOutreach, z = t.admin.zaad;
  const editing = !contact || initialMode === "edit";
  const heading = useRef<HTMLHeadingElement>(null);
  useEffect(() => { heading.current?.focus(); }, [editing]);
  const [detail, setDetail] = useState<Detail | null>(contact), [loaded, setLoaded] = useState(!contact), [busy, setBusyState] = useState(false), [error, setError] = useState("");
  const [student, setStudent] = useState(emptyRegistration), [name, setName] = useState(contact?.name ?? ""), [phone, setPhone] = useState(contact?.phone ?? ""), [district, setDistrict] = useState(contact?.district ?? "");
  const [topics, setTopics] = useState<string[]>(contact?.requestedTopics ?? []), [status, setStatus] = useState(contact?.status ?? "PENDING_REVIEW"), [consent, setConsent] = useState(false), [identity, setIdentity] = useState(false), [phoneConfirmed, setPhoneConfirmed] = useState(false), [attestation, setAttestation] = useState("");
  const [days, setDays] = useState<number[]>([]), [start, setStart] = useState(""), [end, setEnd] = useState("");
  const [studentNumber, setStudentNumber] = useState(contact?.studentNumber ?? ""), [newConsent, setNewConsent] = useState(false), [consentDate, setConsentDate] = useState("");
  const op = useRef<string | null>(null), lock = useRef(false), dirty = useRef(false);
  const [discard, setDiscard] = useState(false), [reload, setReload] = useState(0);
  const finish = () => { setDirty(false); close(); };
  const requestClose = () => { if (lock.current) return; if (dirty.current) setDiscard(true); else finish(); };
  const setBusy = (value: boolean) => { setBusyState(value); setSaving?.(value); };
  useEffect(() => { if (!contact) return; const controller = new AbortController(); outreachRequest<{ contact: Detail }>(tenant, `contacts/${encodeURIComponent(contact.reference.id)}?origin=${contact.reference.origin}`, { signal: controller.signal }).then(({ contact: row }) => { if (controller.signal.aborted) return; setDetail(row); setName(row.name); setPhone(row.phone); setDistrict(row.district ?? ""); setTopics(row.requestedTopics); setAttestation(row.attestation ?? row.registration?.note ?? ""); setStatus(row.status); setIdentity(row.identityVerified); setPhoneConfirmed(row.phoneVerified); const availability = row.availability?.confirmed ?? row.availability?.requested; if (availability) { setDays(availability.weekdays); setStart(availability.windows[0]?.start ?? ""); setEnd(availability.windows[0]?.end ?? ""); } setLoaded(true); }).catch(() => { if (!controller.signal.aborted) setError(z.common.failure); }); return () => controller.abort(); }, [contact, tenant, z.common.failure, reload]);
  function change() { dirty.current = true; setDirty(true); op.current = null; }
  async function save() {
    if (!editing || !writable || lock.current) return; lock.current = true; setBusy(true); setError(""); op.current ??= crypto.randomUUID();
    try {
      if (!contact) {
        const body = tenant === "univ" ? { registration: registrationPayload(student, op.current), attestation } : { operationKey: op.current, name, phone, district, topics, consent, consentVersion: MUNICIPAL_CONSENT_VERSION, availability: topics.includes("elder-watch") ? { weekdays: days, windows: [{ start, end }] } : null };
        await outreachMutation(tenant, "contacts", body);
      } else {
        const body = contact.reference.origin === "UNIVERSITY_REGISTRATION" ? { version: detail!.version, name, phone, status, identityConfirmed: identity, phoneConfirmed, note: attestation, topicIds: topics, ...(detail?.registration?.contact ? { contactId: detail.registration.contact.id, contactVersion: detail.registration.contact.version } : {}) } : { version: detail!.version, name, phone, status, topics, identityVerified: identity, phoneVerified: phoneConfirmed, ...(tenant === "univ" && studentNumber ? { studentNumber } : {}), ...(newConsent ? { consentEvidence: { topics, consentVersion: tenant === "lg" ? MUNICIPAL_CONSENT_VERSION : CONSENT_VERSION, consentedAt: new Date(consentDate).toISOString() } } : {}), attestation, confirmationMethod: attestation, confirmedAt: new Date().toISOString(), ...(tenant === "lg" ? { district, ...(topics.includes("elder-watch") ? { availability: { weekdays: days, windows: [{ start, end }] } } : {}) } : {}) };
        await outreachMutation(tenant, `contacts/${encodeURIComponent(contact.reference.id)}?origin=${contact.reference.origin}`, body, "PATCH");
      }
      setDirty(false); saved();
    } catch { setError(z.residents.formInvalid); } finally { lock.current = false; setBusy(false); }
  }
  const writable = contact ? permissions.update && contact.reference.origin !== "DISASTER_RADIO" : permissions.create;
  return <><section className="max-w-3xl space-y-6" aria-labelledby="contact-page-title"><div className="flex items-center justify-between gap-4"><h2 ref={heading} id="contact-page-title" tabIndex={-1} className="text-lg font-bold">{!contact ? d.contactAdd : editing ? d.contactEdit : d.contactDetails}</h2><button type="button" className={secondary} disabled={busy} onClick={requestClose}>{d.backToContacts}</button></div><p className="text-sm text-fg-muted">{d.consentRequired}</p><form className="space-y-5" onSubmit={event => { event.preventDefault(); void save(); }}>{loaded && error && <Feedback tone="error">{error}</Feedback>}{!loaded ? error ? <OutreachFailure retry={() => { setError(""); setReload(value => value + 1); }} /> : <OutreachLoading /> : <fieldset disabled={busy || !writable || !editing} className="space-y-5 border-0 p-0">
    {tenant === "univ" && !contact ? <RegistrationFields value={student} years={years ?? []} onChange={value => { setStudent(value); change(); }} staff /> : <><label className="block">{m.name}<input required maxLength={100} className={input} value={name} onChange={event => { setName(event.target.value); change(); }} /></label><label className="block">{m.phone}<input required type="tel" className={input} value={phone} onChange={event => { setPhone(event.target.value); change(); }} /></label>{tenant === "lg" && <label className="block">{m.district}<Select required value={district} onChange={event => { setDistrict(event.target.value); change(); }}><option value="">{m.choose}</option>{Object.entries(m.districts).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</Select></label>}
    <fieldset className="space-y-3"><legend className="mb-2 font-medium">{m.notices}</legend>{(tenant === "lg" ? MUNICIPAL_TOPICS : TOPICS).map((topic, index) => <label key={topic} className="flex items-start gap-3"><Checkbox checked={topics.includes(topic)} onChange={event => { setTopics(current => event.target.checked ? [...current, topic] : current.filter(value => value !== topic)); change(); }} /><span>{tenant === "lg" ? m.topics[topic] : u.topicLabels[index]}</span></label>)}</fieldset>
    {tenant === "lg" && topics.includes("elder-watch") && <fieldset className="space-y-3"><legend>{m.days}</legend><div className="flex flex-wrap gap-3">{m.weekdays.map((day, index) => <label key={day} className="flex gap-2"><Checkbox checked={days.includes(index)} onChange={event => { setDays(current => event.target.checked ? [...current, index] : current.filter(value => value !== index)); change(); }} />{day}</label>)}</div><div className="grid grid-cols-2 gap-3"><label>{m.start}<input required type="time" className={input} value={start} onChange={event => { setStart(event.target.value); change(); }} /></label><label>{m.end}<input required type="time" className={input} value={end} onChange={event => { setEnd(event.target.value); change(); }} /></label></div></fieldset>}
    {!contact && <><p className="text-sm leading-6 text-fg-muted">{m.consent}</p><label className="flex gap-3"><Checkbox required checked={consent} onChange={event => { setConsent(event.target.checked); change(); }} />{m.consentLabel}</label></>}</>}
    {contact && <>{tenant === "univ" && ["UNIVERSITY_CONTACT", "IMPORT_CANDIDATE"].includes(contact.reference.origin) && <label className="block">{u.studentNumber}<input className={input} required pattern="[1-7][0-9]{6}" maxLength={7} value={studentNumber} onChange={event => { setStudentNumber(event.target.value); change(); }} /></label>}<label className="block">{d.registrationStatus}<Select value={status} onChange={event => { setStatus(event.target.value); change(); }}><option value="PENDING_REVIEW">{d.pending}</option><option value="ACTIVE">{d.active}</option><option value="WITHDRAWN">{d.withdrawn}</option></Select></label><label className="flex gap-3"><Checkbox checked={identity} onChange={event => { setIdentity(event.target.checked); change(); }} />{tenant === "lg" ? m.identityConfirmed : u.identityConfirmed}</label><label className="flex gap-3"><Checkbox checked={phoneConfirmed} onChange={event => { setPhoneConfirmed(event.target.checked); change(); }} />{u.phoneConfirmed}</label>{contact.reference.origin !== "UNIVERSITY_REGISTRATION" && <><label className="flex gap-3"><Checkbox checked={newConsent} onChange={event => { setNewConsent(event.target.checked); change(); }} />{u.attestation}</label>{newConsent && <label className="block">{u.note}<input className={input} required type="datetime-local" value={consentDate} onChange={event => { setConsentDate(event.target.value); change(); }} /></label>}</>}</>}
    {(contact || tenant === "univ") && <label className="block">{u.attestation}<textarea required className={input} value={attestation} rows={3} maxLength={2000} onChange={event => { setAttestation(event.target.value); change(); }} /></label>}
    </fieldset>}<div className="flex gap-3">{writable && (editing ? <button className={primary} disabled={busy || !loaded}>{z.common.save}</button> : <button type="button" className={primary} disabled={!loaded} onClick={edit}>{z.common.edit}</button>)}</div></form></section>{discard && <ModalDialog title={d.confirmDiscard} description={name} onRequestClose={() => setDiscard(false)}><div className="flex justify-end gap-3"><button className={secondary} onClick={() => setDiscard(false)}>{z.common.cancel}</button><button className={primary} onClick={finish}>{d.discard}</button></div></ModalDialog>}</>;
}
